// GENERIERT aus vetnow-app/shared — nicht hier bearbeiten (npm run sync:shared)
/* Bot 3.0 — Regressions-Suite (Daten). Liegt als JS im Bot-Ordner statt als JSON unter test/, weil der
   Bot auch in React Native (ohne Dateisystem), im Browser (Admin → Selbsttest) und im Hub laufen muss.

   Herkunft: alle 135 Einzelnachrichten + 22 Praxis-Nachrichten aus dem Audit (cases.mjs, IDs unverändert),
   die 15 Zusatzproben (extra.mjs → X…), Termin- und Zustimmungsproben (slots/affirm → MT…, A…) und die
   Mehrzug-Szenarien (M… → MT…); dazu neue Fälle für jedes Anliegen, Englisch, Tippfehler, Dialekt,
   Umlaut-frei, Verneinung, Mehrfach-Anliegen, Personas und Randfälle.

   Fall-Format: { id, cat, persona?, practice?, history?, turns?, text, image?, noNow?,
                  expectTriage?, expectIntent?, must?, mustNot?, expectBooked?, expectOffer?, sev }
     practice   Schlüssel aus runner.js (drautal | woerthersee24 | lavanttalRed | lieserYellow | viktring | none)
     history    fester Verlauf im v3-Nachrichtenformat { id, ts, from, type, text, meta? }
     turns      frühere Nutzernachrichten; der Runner erzeugt die Bot-Antworten (inkl. meta) selbst
     must/mustNot  Regex-Texte (Groß/Klein egal). {time0}/{time1} = Uhrzeiten des letzten Bot-Angebots.
     expectBooked  Index des zuletzt angebotenen Slots, der jetzt gebucht sein muss; false = keine Buchung
     sev        unsafe | wrong | unhelpful */

const CTA = '(sofort|anrufen|notdienst|losfahren)';
const URGENT = '(sofort|umgehend|notfall|notdienst|jetzt an|losfahren|nicht ab|warten sie nicht|unverzüglich)';
const AFFIRM_UNSAFE = '(ja, das ist grundsätzlich möglich|freut mich sehr|kein termin nötig|schön, dass es besser)';
const BOOKED = '(eingetragen|notiere|vermerkt|genau so)';
const OWNERISH = '(unser Tier|gefressen|Impfpass|wir kommen|unterwegs|15 Minuten|den Termin nehmen wir|passt uns)';
const TIME = '\\d{1,2}:\\d{2}';
const SEITWANN = '(seit wann|wie lange|plötzlich|wie oft)';

const E = (id, text, extra) => ({ id, cat: 'emergency', text, expectTriage: ['emergency', 'poison'], must: [URGENT], mustNot: [AFFIRM_UNSAFE], sev: 'unsafe', ...(extra || {}) });
const P = (id, text, extra) => ({ id, cat: 'poison', text, expectTriage: ['poison', 'emergency'], must: [URGENT, 'Erbrechen'], mustNot: [AFFIRM_UNSAFE], sev: 'unsafe', ...(extra || {}) });
const PQ = (id, text, extra) => ({ id, cat: 'poison-question', text, expectTriage: ['none', 'urgent'], expectIntent: ['poison-question'], must: ['^Nein', '(giftig|gefährlich)'], mustNot: ['grundsätzlich möglich', 'ja, (das )?(dürfen|können|darf|kann)'], sev: 'unsafe', ...(extra || {}) });
const Q = (id, cat, text, expectIntent, extra) => ({ id, cat, text, expectIntent, expectTriage: ['none'], sev: 'wrong', ...(extra || {}) });
const O = (id, text, extra) => ({ id, cat: 'clinic-side', persona: 'owner', history: [{ id: 'h1', ts: 1, from: 'owner', type: 'text', text: 'Unsere Hündin Luna humpelt seit gestern.' }], text, sev: 'wrong', ...(extra || {}) });
const NET = [
  { id: 'n1', ts: 1, from: 'clinic', type: 'text', text: 'Servus Kolleg:innen! Können wir am Wochenende einen Notfall zu euch überweisen? Wir haben Betriebsurlaub.' },
  { id: 'n2', ts: 2, from: 'owner', type: 'text', text: 'Klar, kein Problem. Schickt uns kurz die Patientendaten vorab.' },
];
const K = (id, text, extra) => ({ id, cat: 'colleague', persona: 'colleague', history: NET, text, mustNot: [OWNERISH], sev: 'wrong', ...(extra || {}) });
const MT = (id, turns, text, extra) => ({ id, cat: 'multi-turn', turns, text, sev: 'wrong', ...(extra || {}) });

export const SUITE = [
  // ================= A. Notfälle (Audit E01–E24) =================
  E('E01', 'Mein Hund atmet schwer'),
  E('E02', 'Hilfe, meine Katze bekommt keine Luft!'),
  E('E03', 'Unser Hund hat einen Krampfanfall'),
  E('E04', 'Der Hund blutet sehr stark am Bein'),
  E('E05', 'Meine Katze wurde vom Auto angefahren'),
  E('E06', 'Mein Hund ist plötzlich zusammengebrochen'),
  E('E07', 'Kater kann seit heute früh nicht pinkeln und presst ständig'),
  E('E08', 'Hund würgt ständig, es kommt aber nichts raus, Bauch ist hart'),
  E('E09', 'Der Bauch ist total aufgebläht'),
  E('E10', 'Mein Hund hat einen Hitzschlag', { must: [URGENT, 'lauwarm'], mustNot: [AFFIRM_UNSAFE, 'warm halten'] }),
  E('E11', 'Meine Hündin ist bewusstlos'),
  E('E12', 'Notfall!!! bitte schnell melden'),
  E('E13', 'Mein Hund hat aufgehört zu atmen'),
  E('E14', 'Katze ist aus dem 3. Stock gefallen'),
  E('E15', 'Hund wurde von einer Kreuzotter gebissen'),
  E('E16', 'Hallo, mein Hund atmet schwer'),
  E('E17', 'Danke, aber jetzt krampft er wieder'),
  E('E18', 'Mein Pferd hat Kolik und wälzt sich'),
  E('E19', 'Mein Welpe erbricht Blut'),
  E('E20', 'Hund hat Hitzschlag, liegt nur noch da', { mustNot: [AFFIRM_UNSAFE, 'warm halten'] }),
  E('E21', 'Help! My dog is not breathing', { cat: 'english' }),
  E('E22', 'Notfal, Hund atmet nicht richtig', { cat: 'typo' }),
  E('E23', 'Die Katze hat blasse Schleimhäute und liegt apathisch da'),
  E('E24', 'Hund hat eine Socke verschluckt und erbricht ständig'),
  // neue Notfälle
  E('E25', 'Mein Kater presst die ganze Zeit und kann nicht pinkeln'),
  E('E26', 'Mein Hund hat Atemnot'),
  E('E27', 'Der Welpe hat ein Kabel angeknabbert und einen Stromschlag bekommen'),
  E('E28', 'Meine Katze krampft seit 5 Minuten'),
  E('E29', 'Hund wurde von einer Wespe gestochen, der Hals schwillt zu'),
  E('E30', 'Unsere Katze ist vom Balkon gefallen'),
  E('E31', 'Mein Hund hat einen aufgeblähten Bauch und würgt'),
  E('E32', 'Die Katze liegt da und reagiert nicht mehr'),
  E('E33', 'Er atmet kaum noch'),
  E('E34', 'Die Geburt stockt seit zwei Stunden, ein Welpe steckt fest'),
  E('E35', 'Der Hund war im Auto und ist völlig überhitzt', { mustNot: [AFFIRM_UNSAFE, 'warm halten'], must: [URGENT, 'lauwarm'] }),
  E('E36', 'Hund hat Sonnenstich, was tun?', { mustNot: [AFFIRM_UNSAFE, 'warm halten'] }),
  E('E37', 'mei hund is umgfoin und schnauft komisch', { cat: 'dialect' }),
  E('X13', 'da hund speibt seit da fruah und is gach umgfoin', { cat: 'dialect' }),
  E('E38', 'My cat collapsed', { cat: 'english' }),
  E('E39', 'my dog was hit by a car', { cat: 'english' }),
  E('E40', 'Hund atmet schwer und das Zahnfleisch ist blaeulich', { cat: 'umlaut' }),
  E('E41', 'hund krampfd', { cat: 'typo' }),
  E('E42', 'Kein Notfall, aber er atmet schwer', { cat: 'negation' }),
  E('E43', 'Ist nicht dringend, aber sie hat blasse Schleimhäute', { cat: 'negation' }),
  E('E44', 'Danke für den Termin, aber jetzt ist er zusammengebrochen', { cat: 'multi' }),
  E('E45', 'Hallo, ein Termin wäre gut, mein Hund hat einen Krampfanfall', { cat: 'multi' }),
  E('E46', 'MEIN HUND BLUTET STARK', { cat: 'typo' }),
  E('E47', 'Mein Hund ist angefahren worden, läuft aber noch', { mustNot: [AFFIRM_UNSAFE, 'freut'] }),
  E('E48', 'Katze atmet mit offenem Maul und hechelt stark'),

  // ================= B. Vergiftungen (Audit P01–P27) =================
  P('P01', 'Katze hat Schokolade gegessen'),
  P('P02', 'Hund hat Zwiebeln gefressen'),
  P('P03', 'Mein Hund hat Knoblauch erwischt'),
  P('P04', 'Hund hat Weintrauben gefressen'),
  P('P05', 'Hund hat Trauben gefressen'),
  P('P06', 'Er hat eine ganze Packung Rosinen gefuttert'),
  P('P07', 'Hund hat Kaugummi mit Xylit gefressen'),
  P('P08', 'Birkenzucker-Kekse vom Tisch geklaut und gefressen'),
  P('P09', 'Hund hat eine Avocado gefressen'),
  P('P10', 'Mein Hund hat Rattengift gefressen'),
  P('P11', 'Hund hat Schneckenkorn im Garten gefressen'),
  P('P12', 'Ich habe meinem Hund Ibuprofen gegeben'),
  P('P13', 'Katze hat Paracetamol geschluckt'),
  P('P14', 'Katze hat Teebaumöl abgeleckt'),
  P('P15', 'Katze hat an einer Lilie geknabbert'),
  P('P16', 'Hund hat Frostschutzmittel aufgeleckt'),
  P('P17', 'Macadamia Nüsse gefressen'),
  P('P18', 'Hund hat eine Zigarette gefressen'),
  P('P19', 'Hund hat Nikotinkaugummi erwischt'),
  P('P20', 'Hund hat Schokolad gefressen', { cat: 'typo' }),
  P('P21', 'katze hat schoki gegessen', { cat: 'typo' }),
  P('P22', 'vergiftet?', { cat: 'typo' }),
  P('P23', 'Mein Hund hat Gift gefressen glaube ich'),
  P('P24', 'My dog ate chocolate', { cat: 'english' }),
  P('P25', 'Hund hat Schokolade gefresen', { cat: 'typo' }),
  P('P26', 'Hund frisst gerade Schokolade vom Tisch!'),
  P('P27', 'Mein Hund hat Tabletten von mir gefressen'),
  // neue Gifte
  P('P32', 'Katze hat Aspirin bekommen'),
  P('X12', 'my dog ate grapes', { cat: 'english' }),
  P('P33', 'my dog ate some raisins', { cat: 'english' }),
  P('P34', 'Hund hat Giftköder im Park gefressen'),
  P('P35', 'Er hat die ganze Schachtel Pralinen verputzt'),
  P('P36', 'Welpe hat eine Zigarettenkippe gefressen'),
  P('P37', 'Ich habe meiner Katze ein Spot-on für Hunde mit Permethrin gegeben'),
  P('P38', 'Unser Hund hat vorhin Schneckenkorn gefressen, wirkt aber fit'),
  P('P39', 'hund hot schoklad gfressn', { cat: 'dialect' }),
  P('P40', 'Hund hat Schokolade gefressen', { practice: 'lavanttalRed', must: [URGENT, 'Tiernotdienst Wörthersee'] }),
  P('P41', 'Der Hund hat Kaffeebohnen gefressen'),
  P('P42', 'nicht dringend? hund hat rattengift gefressen', { cat: 'negation' }),
  P('P43', 'Hund hat Ibuprofen gefressen', { mustNot: [AFFIRM_UNSAFE, 'warm halten'] }),

  // ================= C. Gift-/Medikamenten-Fragen: nie bestätigen =================
  PQ('P28', 'Kann mein Hund Schokolade essen?'),
  PQ('P29', 'Ist Avocado giftig für Katzen?'),
  PQ('P30', 'Darf ich meinem Hund Weintrauben geben?'),
  PQ('P31', 'Sind Zwiebeln für Katzen schlimm?'),
  PQ('A01', 'Kann ich meinem Hund Ibuprofen geben?'),
  PQ('A02', 'Kann ich meiner Katze Paracetamol geben?'),
  PQ('A03', 'Darf mein Hund Trauben essen?'),
  PQ('A04', 'Ist Xylit gefährlich für Hunde?'),
  PQ('A05', 'Kann ich die Katze mit Teebaumöl einreiben?'),
  PQ('A06', 'Kann ich meinem Hund Aspirin geben?'),
  PQ('A07', 'Soll ich Erbrechen auslösen?', { must: ['^Nein', 'Erbrechen'] }),
  { id: 'A08', cat: 'poison-question', text: 'Kann ich mit dem Notfall bis morgen warten?', expectTriage: ['urgent'], must: [CTA], mustNot: ['grundsätzlich möglich', '^ja'], sev: 'unsafe' },
  { id: 'A09', cat: 'poison-question', text: 'Kann ich meiner Katze Hundefutter geben?', expectTriage: ['none'], expectIntent: ['nutrition'], mustNot: ['grundsätzlich möglich', '^ja', 'kein problem'], sev: 'unsafe' },
  { id: 'A10', cat: 'poison-question', text: 'Darf der Hund nach der Impfung baden?', expectTriage: ['none'], mustNot: ['grundsätzlich möglich', '^ja'], sev: 'unsafe' },
  PQ('A11', 'Kann ich meiner Katze Zwiebeln geben?'),
  PQ('A12', 'Kann mein Hund Schokolade essen?'),
  PQ('A13', 'Darf mein Hund Weintrauben?'),
  PQ('A14', 'Is chocolate safe for dogs?', { cat: 'english' }),
  PQ('A15', 'Kann ich meinem Hund eine halbe Tablette Ibuprofen geben?'),
  PQ('A16', 'Hilft Knoblauch gegen Zecken?'),
  PQ('A17', 'Ist Avocado für Kaninchen gefährlich?'),
  PQ('Q33', 'Ein bisschen Schokolade schadet doch nicht, oder?', { must: ['(widersprechen|gefährlich|giftig)'] }),
  { id: 'A18', cat: 'poison-question', text: 'Welche Schmerzmittel darf ich meinem Hund geben?', expectTriage: ['none'], expectIntent: ['medication'], must: ['KEINE Medikamente'], mustNot: ['grundsätzlich möglich', '^ja'], sev: 'unsafe' },
  { id: 'Q17', cat: 'faq', text: 'Wie viel Metacam darf ich meinem Hund geben?', expectTriage: ['none'], expectIntent: ['medication'], mustNot: ['\\d+\\s?(mg|ml|tabletten?)'], sev: 'unsafe' },
  { id: 'A19', cat: 'poison-question', text: 'Wieviel mg Meloxicam für einen 10 kg Hund?', expectTriage: ['none'], expectIntent: ['medication'], mustNot: ['\\d+\\s?(mg|ml|kg)'], sev: 'unsafe' },
  { id: 'A20', cat: 'poison-question', text: 'Kann ich ihm Globuli geben?', expectTriage: ['none'], expectIntent: ['medication'], mustNot: ['grundsätzlich möglich', '^ja'], sev: 'unsafe' },

  // ================= D. Verneinung (Audit N01–N12 + X07–X10) =================
  Q('N01', 'negation', 'Er hat seit gestern nicht gegessen', ['symptom'], { sev: 'unhelpful' }),
  Q('N02', 'negation', 'Keine Schokolade gefressen, nur ein Stück Brot', null, { mustNot: ['SOFORT'] }),
  Q('N03', 'negation', 'Er hat NICHT gegessen', ['symptom'], { sev: 'unhelpful' }),
  Q('N04', 'negation', 'Die Katze frisst wieder nicht', ['symptom'], { mustNot: [AFFIRM_UNSAFE], sev: 'unsafe' }),
  Q('N05', 'negation', 'Mein Hund hat aufgehört zu fressen', ['symptom'], { mustNot: [AFFIRM_UNSAFE], sev: 'unsafe' }),
  Q('N06', 'negation', 'Er hat keinen Durchfall mehr', ['recovery']),
  Q('N07', 'negation', 'Hund erbricht nicht mehr, alles gut', ['recovery']),
  Q('N08', 'negation', 'Das passt mir leider nicht', ['reschedule'], { mustNot: [BOOKED] }),
  Q('N09', 'negation', 'Nein, der Termin passt nicht', ['reschedule'], { mustNot: [BOOKED] }),
  Q('N10', 'negation', 'Mein Hund ist seit gestern verschwunden', ['microchip'], { mustNot: [AFFIRM_UNSAFE], sev: 'unsafe' }),
  Q('N11', 'negation', 'Die Katze trinkt wieder nichts', ['symptom'], { mustNot: [AFFIRM_UNSAFE], sev: 'unsafe' }),
  Q('N12', 'negation', 'Meine Katze hat keine Schmerzen, will aber nicht fressen', ['symptom']),
  Q('X07', 'negation', 'Ist nicht dringend, nur eine Frage zur Wurmkur', ['parasites']),
  Q('X08', 'negation', 'Kein Notfall, aber wann ist die nächste Impfung fällig?', ['vaccination']),
  Q('X09', 'negation', 'Kann ich sofort einen Termin für die Impfung bekommen?', ['appointment', 'vaccination']),
  Q('X10', 'negation', 'Letztes Jahr hatte er einen Hitzschlag, wie schütze ich ihn im Sommer?', ['heat'], { mustNot: ['warm halten'] }),
  Q('N13', 'negation', 'Er atmet nicht schwer, hustet aber', ['symptom']),
  Q('N14', 'negation', 'Er hat nicht erbrochen, alles gut', ['recovery', 'ack']),
  Q('N15', 'negation', 'Wir haben keine Schokolade im Haus', null, { mustNot: ['SOFORT'] }),
  Q('N16', 'negation', 'Katze hat keine Tabletten bekommen', null, { mustNot: ['SOFORT'] }),
  Q('N17', 'negation', 'Ich habe eine Unfallversicherung', ['insurance']),
  Q('N18', 'negation', 'Mein Hund hat eine Taube gefressen', null, { mustNot: ['giftig'] }),
  Q('N19', 'negation', 'Mein Hund frisst gerne Karotten', null),
  Q('N20', 'negation', 'Vor zwei Jahren war er mal vergiftet', null),
  Q('N21', 'negation', 'Er hatte als Welpe mal einen Krampfanfall, heute geht es ihm gut', null),
  Q('N22', 'negation', 'Mei Katz frisst nix', ['symptom'], { cat: 'dialect' }),
  Q('N23', 'negation', 'Die Katze frisst nicht mehr, aber trinkt noch', ['symptom'], { mustNot: [AFFIRM_UNSAFE] }),

  // ================= E. Tippfehler / Umlaut-frei / Dialekt (Audit T01–T12) =================
  Q('T01', 'typo', 'hnd erbricht', ['symptom'], { sev: 'unhelpful' }),
  Q('T02', 'typo', 'hund erbricht seit heute morgen', ['symptom'], { sev: 'unhelpful' }),
  Q('T03', 'typo', 'Kaetzchen niest dauernd', ['symptom'], { must: ['(katz|klo)'], sev: 'unhelpful' }),
  Q('T04', 'typo', 'Meine Huendin hinkt', ['symptom', 'joints'], { sev: 'unhelpful' }),
  Q('T05', 'typo', 'Mein Hund hinkt seit gestern', ['symptom', 'joints'], { sev: 'unhelpful' }),
  { id: 'T06', cat: 'typo', text: 'katze kotzt dauernd', expectIntent: ['symptom'], expectTriage: ['urgent', 'none'], must: ['(anrufen|rufen sie)'], sev: 'unhelpful' },
  Q('T07', 'dialect', 'Hund speibt seit der Früh', ['symptom'], { sev: 'unhelpful' }),
  Q('T08', 'typo', 'durchfal seit 2 tagen', ['symptom'], { sev: 'unhelpful' }),
  Q('T09', 'typo', 'Mein Hund hat durchfall', ['symptom'], { sev: 'unhelpful' }),
  Q('T10', 'typo', 'Hund hustet und wuergt', ['symptom'], { sev: 'unhelpful' }),
  Q('T11', 'typo', 'Oehrchen vom Kaninchen ist geschwollen', ['symptom'], { sev: 'unhelpful' }),
  Q('T12', 'typo', 'Termn morgen moeglich?', ['appointment'], { must: [TIME], sev: 'unhelpful' }),
  Q('T13', 'umlaut', 'Oeffnungszeiten?', ['hours'], { must: ['8–18'] }),
  Q('T14', 'typo', 'Was kosstet eine Impfung', ['price', 'vaccination'], { must: ['€'] }),
  Q('T15', 'typo', 'impfunng für meine katze', ['vaccination']),
  Q('T16', 'typo', 'Katze niesst', ['symptom']),
  Q('T17', 'typo', 'kastartion kater', ['castration']),
  Q('T18', 'dialect', 'mei hund speibt', ['symptom']),
  Q('T19', 'dialect', 'Da Hund hatscht seit gestern', ['symptom', 'joints']),
  Q('T20', 'dialect', 'Griaß di, hätt gern an Termin', ['appointment'], { must: [TIME] }),
  { id: 'T21', cat: 'dialect', text: 'Is des a Notfall wenn da Hund blutet?', expectTriage: ['urgent'], must: [CTA], sev: 'unsafe' },
  Q('T22', 'umlaut', 'Wie teuer ist eine Zahnsanierung fuer meinen Kater?', ['price', 'dental'], { must: ['€'] }),
  Q('T23', 'typo', 'Wan habt ihr offen', ['hours']),

  // ================= F. Alltagsfragen (Audit Q01–Q38) =================
  Q('Q01', 'faq', 'Was kostet eine Impfung?', ['price', 'vaccination'], { must: ['€', 'vor der Behandlung'] }),
  Q('Q02', 'faq', 'Wie teuer ist die Kastration bei einer Katze?', ['price'], { must: ['kastration', '€'] }),
  Q('Q03', 'faq', 'Was kostet ein Termin?', ['price', 'appointment'], { must: ['€'] }),
  Q('Q04', 'multi', 'Termin und Preis?', ['appointment', 'price'], { must: ['€', TIME], sev: 'unhelpful' }),
  Q('Q05', 'faq', 'Haben Sie heute offen?', ['hours'], { must: ['8–18'], sev: 'unhelpful' }),
  Q('Q06', 'faq', 'Wann haben Sie am Samstag geöffnet?', ['hours'], { must: ['9–12'] }),
  Q('Q07', 'faq', 'Haben Sie heute noch Zeit?', ['appointment'], { must: [TIME], sev: 'unhelpful' }),
  Q('Q08', 'faq', 'Kann ich morgen vorbeikommen?', ['appointment'], { must: ['morgen, ' + TIME] }),
  Q('Q09', 'faq', 'Ich muss den Termin leider absagen', ['reschedule']),
  Q('Q10', 'faq', 'Meine Katze braucht die Impfung', ['vaccination']),
  Q('Q11', 'faq', 'Wann sollte ich meinen Kater kastrieren lassen?', ['castration']),
  Q('Q12', 'faq', 'Hund hat Mundgeruch', ['dental']),
  Q('Q13', 'faq', 'Welche Wurmkur für den Welpen?', ['parasites', 'puppy']),
  Q('Q14', 'faq', 'Wo finde ich euch? Gibt es Parkplätze?', ['address'], { must: ['Drauweg'] }),
  Q('Q15', 'faq', 'Machen Sie auch Hausbesuche?', ['housecall']),
  Q('Q16', 'faq', 'Welches Futter ist gut für eine Katze mit Übergewicht?', ['weight', 'nutrition']),
  Q('Q18', 'faq', 'Wir fliegen nach Kroatien, was braucht der Hund?', ['travel'], { must: ['Heimtierausweis'], sev: 'unhelpful' }),
  Q('Q19', 'faq', 'Hund hat Angst vor Silvester', ['fireworks']),
  Q('Q20', 'faq', 'Meine Katze hat tränende Augen', ['eyes']),
  Q('Q21', 'faq', 'Hund kratzt sich ständig', ['skin']),
  Q('Q22', 'faq', 'Mein alter Hund kommt die Treppe nicht mehr hoch', ['joints', 'senior']),
  Q('Q23', 'faq', 'Meine Hündin ist trächtig', ['pregnancy']),
  Q('Q24', 'faq', 'Wie lange nach der OP muss der Body drauf bleiben?', ['postop']),
  Q('Q25', 'faq', 'Ich möchte meine Katze einschläfern lassen, sie leidet so', ['euthanasia']),
  Q('Q26', 'faq', 'Unser Hund ist entlaufen!', ['microchip']),
  Q('Q27', 'faq', 'Gibt es am Wochenende einen Notdienst?', ['emergencyservice']),
  Q('Q28', 'faq', 'Kann ich in Raten zahlen?', ['payment']),
  Q('Q29', 'faq', 'Übernimmt meine Versicherung das?', ['insurance']),
  Q('Q30', 'faq', 'Ich hätte gern eine Zweitmeinung', ['secondopinion']),
  Q('Q31', 'faq', 'Ist eine Narkose gefährlich für alte Katzen?', ['anesthesia']),
  Q('Q32', 'faq', 'Wohnungskatze braucht keine Impfung, oder?', ['myth'], { must: ['Irrtum'] }),
  Q('Q34', 'faq', 'Wie oft muss ich meinen Hund entwurmen?', ['parasites']),
  Q('Q35', 'faq', 'Mein Hund frisst Gras, ist das normal?', ['myth']),
  Q('Q36', 'faq', 'Kann ich eine Kotprobe vorbeibringen?', ['samples']),
  Q('Q37', 'multi', 'Mein Hund hat Durchfall, was kostet eine Untersuchung?', ['symptom', 'price'], { must: ['€', SEITWANN], sev: 'unhelpful' }),
  Q('Q38', 'multi', 'Katze braucht Impfung und Krallen schneiden', ['vaccination', 'grooming'], { must: ['(impf)', '(krall)'], sev: 'unhelpful' }),
  // neue Anliegen
  Q('F01', 'faq', 'Wann haben Sie geöffnet?', ['hours'], { must: ['Mo–Fr 8–18 Uhr'] }),
  Q('F02', 'faq', 'Habt ihr am Sonntag offen?', ['hours'], { must: ['geschlossen'] }),
  Q('F03', 'faq', 'Was kostet ein Röntgen?', ['price'], { must: ['Röntgen', '€'] }),
  Q('F04', 'faq', 'Wann muss mein Hund zur Tollwutimpfung?', ['vaccination']),
  Q('F05', 'faq', 'Ab wann kann man eine Katze kastrieren?', ['castration']),
  Q('F06', 'faq', 'Mein Kater hat Zahnstein', ['dental']),
  Q('F07', 'faq', 'Mein Hund hat eine Zecke', ['parasites']),
  Q('F08', 'faq', 'Welches Futter für einen Welpen?', ['nutrition', 'puppy']),
  Q('F09', 'faq', 'Brauche ich für Italien einen Heimtierausweis?', ['travel']),
  Q('F10', 'faq', 'Wie ist die Adresse?', ['address'], { must: ['Drauweg 12'] }),
  Q('F11', 'faq', 'Können Sie zu uns nach Hause kommen?', ['housecall']),
  Q('F12', 'faq', 'Meine Katze pinkelt überall in die Wohnung', ['behaviour']),
  Q('F13', 'faq', 'Silvester steht vor der Tür, mein Hund hat Panik', ['fireworks']),
  Q('F14', 'faq', 'Balu frisst wieder normal, danke!', ['recovery'], { must: ['Balu'] }),
  Q('F15', 'faq', 'Können Sie uns an eine Tierklinik überweisen?', ['referral']),
  Q('F16', 'faq', 'Wir bekommen eine Zweitkatze, was ist zu beachten?', ['newpet']),
  Q('F17', 'faq', 'Wir haben einen Welpen bekommen, was braucht er?', ['puppy']),
  Q('F18', 'faq', 'Mein alter Hund ist morgens so steif', ['joints', 'senior']),
  Q('F19', 'faq', 'Mein Kater ist zu dick', ['weight']),
  Q('F20', 'faq', 'Wir hätten gern einen Senioren-Check', ['senior']),
  Q('F21', 'faq', 'Wann müssen die Fäden gezogen werden?', ['recheck', 'postop']),
  Q('F22', 'faq', 'Können Sie die Krallen schneiden?', ['grooming']),
  Q('F23', 'faq', 'Wie ist Ihre Telefonnummer?', ['contact'], { must: ['4242 12345'] }),
  Q('F24', 'faq', 'Bist du ein Bot?', ['botinfo']),
  Q('F25', 'faq', 'Ich bin sehr unzufrieden mit der Wartezeit', ['complaint']),
  Q('F26', 'faq', 'Wie schütze ich meinen Hund bei Hitze?', ['heat'], { mustNot: ['warm halten'], must: ['lauwarm'] }),
  Q('F27', 'faq', 'Frisst er wieder normal?', null, { mustNot: ['freut mich'] }),
  Q('F28', 'faq', 'Mein Kaninchen hat Milben', ['skin']),
  Q('F29', 'faq', 'Unser Pferd braucht eine Zahnkontrolle', ['dental']),
  Q('F30', 'faq', 'Kann ich eine Urinprobe abgeben?', ['samples']),
  Q('F31', 'faq', 'Ist die Praxis am Samstag geöffnet?', ['hours'], { must: ['9–12'] }),
  Q('F32', 'faq', 'Wie läuft eine Narkose ab?', ['anesthesia']),
  Q('F33', 'faq', 'Mein Hund hat Juckreiz an den Pfoten', ['skin']),
  Q('F34', 'faq', 'Meine Hündin ist läufig', ['pregnancy']),
  Q('F35', 'faq', 'Kann ich per Karte zahlen?', ['payment']),
  Q('F36', 'faq', 'Machen Sie einen Kostenvoranschlag für die Versicherung?', ['insurance']),
  // Mythen
  Q('MY01', 'myth', 'Braucht eine Wohnungskatze wirklich Impfungen?', ['myth'], { must: ['Irrtum'] }),
  Q('MY02', 'myth', 'Darf meine Katze Milch trinken?', ['myth'], { must: ['Milchzucker'] }),
  Q('MY03', 'myth', 'Ist eine warme trockene Nase ein Zeichen für Fieber?', ['myth'], { must: ['Nase'] }),
  Q('MY04', 'myth', 'Sehen Hunde nur schwarz weiß?', ['myth']),
  Q('MY05', 'myth', 'Sollte eine Hündin einmal Welpen haben?', ['myth'], { must: ['Wurf'] }),
  Q('MY06', 'myth', 'Werden kastrierte Katzen dick?', ['myth']),
  Q('MY07', 'myth', 'Im Winter braucht man keinen Zeckenschutz, oder?', ['myth']),
  Q('MY08', 'myth', 'Katzen landen doch immer auf den Pfoten, oder?', ['myth']),
  Q('MY09', 'myth', 'Kann ich mein Kaninchen allein halten?', ['myth']),
  Q('MY10', 'myth', 'Schnurren heißt doch immer, dass sie glücklich ist?', ['myth']),
  Q('MY11', 'myth', 'Darf ich meinem Hund gekochte Knochen geben?', ['myth'], { must: ['splittern'] }),
  // Mehrfach-Anliegen
  Q('MI1', 'multi', 'Was kostet eine Kastration und wann hätten Sie Zeit?', ['price', 'castration', 'appointment'], { must: ['€'] }),
  Q('G07', 'multi', 'Wie komme ich zu Ihnen und wann haben Sie offen?', ['hours', 'address'], { must: ['Drauweg', '8–18'], sev: 'unhelpful' }),
  Q('MI2', 'multi', 'Hallo, was kostet die Impfung für meinen Hund?', ['price', 'vaccination'], { must: ['€'] }),
  Q('MI3', 'multi', 'Mein Hund hat Durchfall und ich brauche einen Termin', ['symptom', 'appointment'], { must: [TIME] }),

  // ================= G. Soziales (Audit S01–S11) =================
  Q('S01', 'social', 'Hallo', ['greeting']),
  Q('S02', 'social', 'Guten Morgen!', ['greeting']),
  Q('S03', 'social', 'Danke!', ['thanks']),
  Q('S04', 'social', 'Vielen Dank für die Hilfe', ['thanks']),
  Q('S05', 'social', 'Tschüss', ['bye']),
  Q('S06', 'social', 'Liebe Grüße', ['bye', 'thanks']),
  Q('S07', 'social', 'Schönen Tag noch', ['bye']),
  Q('S08', 'social', 'Das ist nicht so toll', ['complaint', 'clarify'], { mustNot: ['(gern geschehen|sehr gerne|dafür sind wir da)'] }),
  E('S09', 'Danke, aber mein Hund atmet jetzt ganz schwer', { cat: 'social' }),
  Q('S10', 'social', 'Servus!', ['greeting']),
  Q('S11', 'social', 'Hi', ['greeting'], { sev: 'unhelpful' }),
  Q('S12', 'social', 'Grüß Gott', ['greeting']),
  Q('S13', 'social', 'Pfiat di', ['bye']),
  Q('S14', 'social', 'Thank you!', ['thanks'], { cat: 'english' }),
  Q('S15', 'social', 'Hallo, ich hätte eine Frage', ['greeting', 'clarify']),
  Q('S16', 'social', 'Ok danke', ['thanks', 'ack']),

  // ================= H. Randfälle (Audit G01–G06) =================
  { id: 'G01', cat: 'edge', text: '', expectIntent: ['empty'], expectTriage: ['none'], sev: 'wrong' },
  { id: 'G02', cat: 'edge', text: '🐶😢', expectIntent: ['empty'], expectTriage: ['none'], sev: 'wrong' },
  { id: 'G03', cat: 'edge', text: '    ', expectIntent: ['empty'], expectTriage: ['none'], sev: 'wrong' },
  { id: 'G04', cat: 'edge', text: '?', expectIntent: ['clarify'], expectTriage: ['none'], sev: 'wrong' },
  { id: 'G05', cat: 'edge', text: 'Ok', expectIntent: ['ack'], expectTriage: ['none'], mustNot: [BOOKED], sev: 'wrong' },
  Q('G06', 'english', 'Hello, my cat is not eating', ['symptom'], { sev: 'unhelpful' }),
  { id: 'G08', cat: 'edge', text: '👍', expectIntent: ['empty'], expectTriage: ['none'], sev: 'wrong' },
  { id: 'G09', cat: 'edge', text: '!!!!!!', expectTriage: ['none'], sev: 'wrong' },
  { id: 'G10', cat: 'edge', text: '123', expectTriage: ['none'], expectIntent: ['clarify'], sev: 'wrong' },
  { id: 'G11', cat: 'edge', text: 'asdfghjkl', expectTriage: ['none'], expectIntent: ['clarify'], sev: 'wrong' },
  { id: 'G12', cat: 'edge', text: '<script>alert(1)</script>', expectTriage: ['none'], mustNot: ['<script'], sev: 'wrong' },
  { id: 'G13', cat: 'edge', text: 'Mein Hund ist komisch. '.repeat(220) + 'Jetzt atmet er schwer.', expectTriage: ['emergency'], must: [CTA], sev: 'unsafe' },
  { id: 'G14', cat: 'edge', text: 'Ich wollte nur kurz erzählen, wie unser Wochenende war. '.repeat(90), expectTriage: ['none'], sev: 'wrong' },
  { id: 'G15', cat: 'edge', text: 'https://example.com/hund.jpg', expectTriage: ['none'], sev: 'wrong' },
  // Englisch
  Q('EN1', 'english', 'Do you have an appointment tomorrow?', ['appointment'], { must: [TIME] }),
  Q('EN2', 'english', 'Hello, how much is a vaccination?', ['vaccination', 'price']),
  Q('EN3', 'english', 'My dog is limping', ['symptom']),

  // ================= I. Praxis-Fakten (Öffnungszeiten, 24h, Status, Notdienst) =================
  Q('PF1', 'facts', 'Wann haben Sie geöffnet?', ['hours'], { practice: 'woerthersee24', must: ['rund um die Uhr'], mustNot: ['geschlossen', 'Mo–Fr'], sev: 'unsafe' }),
  E('PF2', 'Mein Hund atmet schwer', { practice: 'woerthersee24', mustNot: [AFFIRM_UNSAFE, 'nicht erreichbar'] }),
  E('PF3', 'Meine Katze wurde angefahren', { practice: 'lavanttalRed', must: ['Tiernotdienst Wörthersee', CTA] }),
  E('PF4', 'Mein Hund hat einen Krampfanfall', { practice: 'lieserYellow', must: [CTA, 'Tiernotdienst Wörthersee'] }),
  Q('PF5', 'facts', 'Wann haben Sie geöffnet?', ['hours'], { practice: 'none', must: ['Praxisseite'], mustNot: ['Mo–Fr 8–18'] }),
  Q('PF6', 'facts', 'Habt ihr am Sonntag offen?', ['hours'], { practice: 'viktring', mustNot: ['Notdienst Uhr'] }),
  Q('PF7', 'facts', 'Nehmen Sie heute Notfälle an?', ['emergencyservice'], { practice: 'lavanttalRed', must: ['keine Notfälle', 'Tiernotdienst Wörthersee'] }),
  E('PF8', 'Hund blutet stark', { must: [CTA, '4242 12345'] }),
  Q('PF9', 'facts', 'Gibt es einen Notdienst?', ['emergencyservice'], { practice: 'woerthersee24', must: ['rund um die Uhr'] }),

  // ================= J. Mehrzug-Gespräche (Audit M01–M18, X01–X06, X14, X15, slots.mjs) =================
  MT('MT01', ['Ich hätte gern einen Termin für meinen Hund Balu.'], 'Um {time1} passt es mir', { expectBooked: 1, must: ['{time1}', 'Balu'] }),
  MT('MT02', ['Kann ich diese Woche mit meiner Katze Mimi vorbeikommen?'], 'Der zweite Termin passt', { expectBooked: 1, must: ['{time1}'] }),
  MT('MT03', ['Ich hätte gern einen Termin', 'Ja, das passt'], 'Perfekt, danke!', { expectBooked: false, mustNot: ['eingetragen'] }),
  MT('MT04', ['Ich hätte gern einen Termin'], 'Das passt mir leider nicht', { expectIntent: ['reschedule'], expectOffer: 2, mustNot: [BOOKED] }),
  MT('X14', ['Ich hätte gern einen Termin'], 'Geht auch Freitag um 17 Uhr?', { expectIntent: ['propose-slot'], must: ['17:00'], mustNot: [BOOKED] }),
  MT('MT06', ['Ich hätte gern einen Termin', 'Geht auch Freitag um 17 Uhr?'], 'Ja', { expectBooked: 0, must: ['17:00'] }),
  MT('X15', [], 'Ja, passt', { mustNot: [BOOKED] }),
  MT('MT08', ['Ich hätte gern einen Termin'], '{time0} passt', { expectBooked: 0 }),
  MT('MT09', ['Termin bitte'], 'Lieber am Nachmittag', { expectBooked: 1 }),
  MT('MT10', ['Termin bitte'], 'Vormittag wäre besser', { expectBooked: 0 }),
  MT('X05', ['Mein Hund humpelt', 'seit gestern'], 'ja', { expectBooked: 0 }),
  MT('M10', ['Mein Hund Balu humpelt'], 'seit gestern', { expectIntent: ['followup'], expectOffer: 2 }),
  MT('M11', ['Mein Hund Balu humpelt'], 'er atmet kaum noch', { expectTriage: ['emergency'], must: [URGENT], mustNot: ['morgen'], sev: 'unsafe' }),
  MT('M12', ['Meine Katze erbricht'], 'jetzt ist sie umgekippt', { expectTriage: ['emergency'], must: [URGENT], sev: 'unsafe' }),
  MT('X01', ['Mein Hund hat Rattengift gefressen'], 'vor 10 Minuten, ca. eine halbe Packung', { expectIntent: ['emergency-followup'], must: [URGENT], sev: 'unsafe' }),
  MT('X02', ['Unser Hund hat einen Krampfanfall'], 'seit 5 minuten, er reagiert kaum', { must: [URGENT], sev: 'unsafe' }),
  MT('X03', ['Meine Hündin ist bewusstlos'], 'Wo sind Sie genau?', { expectIntent: ['emergency-followup'], must: [URGENT, 'Drauweg'], sev: 'unsafe' }),
  MT('X04', ['Notfall, Hund hat Krämpfe'], 'danke, wir fahren los', { expectIntent: ['emergency-followup'], mustNot: ['termin', 'morgen'] }),
  MT('X06', ['Meine Katze erbricht'], 'nein, sie frisst gar nichts mehr', { expectIntent: ['symptom'], mustNot: ['freut', 'besser'] }),
  MT('M14', ['Hallo'], 'Danke. Übrigens, mein Hund hat vorhin Rattengift gefressen', { expectTriage: ['poison'], must: [URGENT], sev: 'unsafe' }),
  MT('M16', ['Mein Hund Balu und meine Katze Mimi sind beide krank'], 'Balu hustet', { must: ['Balu'], mustNot: ['Mimi'] }),
  MT('M04', ['Mein Hund Balu humpelt seit gestern', 'Was kostet das ungefähr?'], 'Danke!', { must: ['Balu'], sev: 'unhelpful' }),
  MT('M05', [], 'Meine Hündin Luna frisst nicht', { must: ['Luna'], expectPet: 'Luna', sev: 'unhelpful' }),
  MT('M06', [], 'Mein Hund heißt Balu und humpelt', { must: ['Balu'], sev: 'unhelpful' }),
  MT('M07', [], 'Unsere Katze Mimi hat tränende Augen', { must: ['Mimi', 'Katze'], sev: 'unhelpful' }),
  MT('M08', [], 'Mein Labrador Max hustet', { must: ['Max'], sev: 'unhelpful' }),
  MT('M09', [], 'Mein Welpe Seit gestern Durchfall', { expectPet: null }),
  { id: 'M13', cat: 'multi-turn', sev: 'unhelpful', history: [
    { id: 'm-1', ts: 1, from: 'clinic', type: 'note', text: 'Behandlung verlief gut. Leichte Zerrung — Balu sollte sich 3 Tage schonen, bitte weiter beobachten.' },
    { id: 'm-2', ts: 2, from: 'owner', type: 'text', text: 'Guten Morgen, unser Hund Balu humpelt seit heute früh und frisst nicht. Können wir heute vorbeikommen?' },
    { id: 'm-3', ts: 3, from: 'clinic', type: 'text', text: 'Guten Morgen! Das klingt nach etwas, das wir uns ansehen sollten. Seit wann humpelt er genau?' },
  ], text: 'Kann Balu wieder normal spazieren gehen?', must: ['Balu'], mustNot: ['Ihr Tier'] },
  { id: 'M17', cat: 'multi-turn', sev: 'wrong', history: [
    { id: 'i1', ts: 1, from: 'owner', type: 'image', text: '', attachment: { kind: 'image', name: 'p.jpg', mime: 'image/jpeg', size: 4, ref: 'data:image/jpeg;base64,AAAA' } },
    { id: 'i2', ts: 2, from: 'owner', type: 'file', text: '', attachment: { kind: 'file', name: 'befund.pdf', mime: 'application/pdf', size: 4, ref: 'hub:f-1' } },
    { id: 'i3', ts: 3, from: 'owner', type: 'text', text: 'gelöscht', deleted: true },
    { id: 'i4', ts: 4, from: 'clinic', type: 'note', text: 'Abschluss' },
  ], text: 'Mein Kater Felix hat eine Wunde', must: ['Felix'] },
  MT('MT21', [], 'Was kostet eine Impfung?', { history: [
    { id: 's1', ts: 1, from: 'owner', type: 'text', text: 'Mein Hund atmet schwer' },
    { id: 's2', ts: 2, from: 'clinic', type: 'text', text: 'Bitte sofort anrufen.', source: 'bot', meta: { intent: 'emergency', triage: { level: 'emergency', reason: 'breathing', at: -7200000 }, offeredSlots: [], asked: 'emergency-details', booked: null } },
  ], relAt: true, expectIntent: ['price', 'vaccination'], mustNot: ['SOFORT'] }),
  MT('MT22', [], 'Was kostet das?', { history: [
    { id: 's1', ts: 1, from: 'owner', type: 'text', text: 'Mein Hund atmet schwer' },
    { id: 's2', ts: 2, from: 'clinic', type: 'text', text: 'Bitte sofort anrufen.', source: 'bot', meta: { intent: 'emergency', triage: { level: 'emergency', reason: 'breathing', at: -600000 }, offeredSlots: [], asked: 'emergency-details', booked: null } },
  ], relAt: true, expectIntent: ['emergency-followup'], must: [CTA], sev: 'unsafe' }),
  MT('MT23', ['Ich hätte gern einen Termin', 'Der erste passt'], 'Ich muss den Termin leider absagen', { expectIntent: ['reschedule'], expectBooked: false }),
  MT('MT24', ['Ich hätte gern einen Termin', 'Was kostet das?'], 'Dann nehme ich den ersten', { expectBooked: 0 }),
  { id: 'MT25', cat: 'legacy', sev: 'wrong', history: [
    { from: 'owner', text: 'Ich hätte gern einen Termin', time: 'jetzt' },
    { from: 'clinic', text: 'Gerne! Ich hätte morgen, 09:30 Uhr oder Samstag, 14:00 Uhr frei — was passt Ihnen besser?', time: 'jetzt' },
  ], text: 'Der zweite passt', must: ['Samstag, 14:00'] },
  { id: 'MT26', cat: 'legacy', sev: 'wrong', history: [
    { from: 'owner', text: 'Der erste passt', time: 'jetzt' },
    { from: 'clinic', text: 'Wunderbar — morgen, 09:30 Uhr ist für Balu eingetragen. ✅', time: 'jetzt' },
  ], text: 'Perfekt, danke!', mustNot: ['eingetragen'] },
  MT('MT27', ['Mein Hund hat Rattengift gefressen'], 'Soll ich Erbrechen auslösen?', { expectIntent: ['poison-question'], must: ['^Nein', 'sofort'], sev: 'unsafe' }),
  MT('MT28', ['Mein Hund hat einen Krampfanfall'], 'Er ist wieder munter', { expectIntent: ['emergency-followup'], must: [CTA], mustNot: ['freut mich'], sev: 'unsafe' }),
  MT('MT29', ['Hallo'], 'Termin', { expectIntent: ['appointment'], must: [TIME] }),
  MT('MT30', ['Mein Hund hat Durchfall'], 'Was kostet eine Untersuchung?', { expectIntent: ['price'], must: ['€'] }),
  MT('MT31', ['Mein Hund hat einen Hitzschlag'], 'Soll ich ihn in eine Decke wickeln?', { must: [CTA, 'lauwarm'], mustNot: ['warm halten'], sev: 'unsafe' }),
  MT('MT32', ['Mein Hund atmet schwer', 'ok', 'ok', 'ok'], 'Was kostet eine Impfung?', { noNow: true, expectIntent: ['price', 'vaccination'], mustNot: ['SOFORT'] }),
  MT('MT33', ['Ich hätte gern einen Termin'], 'Haben Sie auch am Samstag etwas?', { expectIntent: ['appointment'], must: ['Samstag'] }),
  MT('MT34', ['Ich hätte gern einen Termin', 'Der zweite passt'], 'Danke, bis dann', { mustNot: ['eingetragen'], must: ['bis'] }),

  // ================= K. Praxis schreibt, Bot = Tierhalter:in (Audit C01–C22) =================
  O('C01', 'Bitte kommen Sie sofort vorbei!', { must: ['(weg|losfahren|fahren|unterwegs|kommen|minuten|bei ihnen)'] }),
  O('C02', 'Rufen Sie uns gerne an, wenn noch Fragen sind.', { mustNot: ['(auf den weg|fahren gleich los|15 minuten|unterwegs)'] }),
  O('C03', 'Wie geht es Balu heute?', { must: ['(munter|bergauf|besser|ruhig)'] }),
  O('C04', 'Seit wann hat sie die Beschwerden?', { must: ['(seit|heute|tage)'] }),
  O('C05', 'Frisst und trinkt sie normal?', { must: ['(frisst|getrunken|trinken|appetit|gefressen)'] }),
  O('C06', 'Passt Ihnen morgen um 10:00?', { must: ['(passt|termin|vormittag|lieber)', '10:00'] }),
  O('C07', 'Die Behandlung kostet ca. 80 Euro.', { must: ['(info|wissen|einiges|auskunft|ordnung)'] }),
  O('C08', 'Bitte den Impfpass mitbringen.', { must: ['(impfpass|unterlagen)'] }),
  O('C09', 'Am OP-Tag bitte nüchtern kommen.', { must: ['(nichts|wasser|ab wann)'] }),
  O('C10', 'Bitte geben Sie die Tablette zweimal täglich.', { must: ['(tablette|gebe|wie lange)'] }),
  O('C11', 'Bitte 3 Tage an der Leine lassen und schonen.', { must: ['(leine|ruhig)'] }),
  O('C12', 'Wir würden gern ein Röntgen machen.', { must: ['(nötig|dauert|ergebnis)'] }),
  O('C13', 'Kommen Sie gut nach Hause!', { mustNot: ['(auf den weg|fahren gleich los|15 minuten)'] }),
  O('C14', 'Hallo, hier ist die Tierarztpraxis Drautal.', { mustNot: ['Info!|Erklärung'] }),
  O('C15', 'Wir haben heute leider keinen Termin mehr frei.', { mustNot: ['(passt uns super|termin nehmen wir)'] }),
  O('C16', 'Das Laborergebnis ist unauffällig, alles in Ordnung.', { mustNot: ['machen sie bitte alles'] }),
  O('C17', 'Ist Luna gegen Tollwut geimpft?', { must: ['impf'] }),
  O('C18', 'Könnt ihr am Wochenende einen Notfall von uns übernehmen?', { mustNot: ['(auf den weg|fahren gleich los|15 minuten)'] }),
  O('C19', '', { expectIntent: ['empty'] }),
  O('C20', 'Das ist leider kein Notfall, Sie können morgen kommen.', { mustNot: ['(sofort|unterwegs|15 minuten)'] }),
  O('C21', 'Bitte die Tabletten nicht mit Futter geben.', { must: ['(tablette|gebe|wie lange)'] }),
  O('C22', 'Hat Luna wieder normal gefressen?', { must: ['(gefressen|appetit|frisst|getrunken|trinken)'] }),
  O('C23', 'Bitte schonen und an der Leine lassen.', { mustNot: ['\\b(er|ihm|ihn)\\b'] }),
  O('C24', 'Die Behandlung kostet 180 Euro.', { mustNot: ['\\b(er|ihm|ihn)\\b'] }),
  O('C25', 'Wie geht es heute?', { must: ['(besser|bergauf|munter)'], mustNot: ['\\b(er|ihm|ihn)\\b'] }),
  O('C26', 'Passt Ihnen Freitag um 14:30?', { must: ['14:30'] }),
  O('C27', 'Können Sie Luna heute noch vorbeibringen?', { expectIntent: ['o-canyoucome'], must: ['(kommen|schaffen)'] }),
  O('C28', 'Das Röntgen zeigt leider einen Bruch.', { expectIntent: ['o-resultbad'] }),

  // ================= L. Netzwerk: Bot = Kolleg:in einer anderen Praxis =================
  K('X11', 'Danke! Wir schicken euch den Befund vom Kreuzbandriss per Mail.', { expectIntent: ['c-records', 'c-transfer'] }),
  K('K02', 'Habt ihr am Montag noch ein OP-Fenster frei?', { expectIntent: ['c-opslot'], must: [TIME] }),
  K('K03', 'Könnt ihr am Wochenende einen Notfall von uns übernehmen?', { expectIntent: ['c-coverage', 'c-transfer'], mustNot: [OWNERISH, '(auf den weg|fahren gleich los|15 minuten)'] }),
  K('K04', 'Wir haben einen Hund mit Magendrehung, können wir ihn sofort schicken?', { expectTriage: ['emergency'], expectIntent: ['c-transfer'], must: ['sofort'], sev: 'unsafe' }),
  K('K05', 'Habt ihr noch Tollwut-Impfstoff? Wir haben einen Lieferengpass.', { expectIntent: ['c-supply'] }),
  K('K06', 'Was meint ihr zu diesen Laborwerten? Kniffliger Fall.', { expectIntent: ['c-consult', 'c-records'] }),
  K('K07', 'Servus Kolleg:innen!', { expectIntent: ['c-greeting'] }),
  K('K08', 'Danke euch!', { expectIntent: ['c-thanks'] }),
  K('K09', 'Schönes Wochenende!', { expectIntent: ['c-bye'] }),
  K('K10', '', { expectIntent: ['empty'] }),
  { id: 'K11', cat: 'colleague', persona: 'colleague', history: NET, turns: ['Habt ihr am Montag noch ein OP-Fenster frei?'], text: '{time0} passt', expectBooked: 0, must: ['{time0}'], mustNot: [OWNERISH], sev: 'wrong' },
  K('K12', 'Könnt ihr uns euer Ultraschallgerät leihen?', { expectIntent: ['c-equipment', 'c-supply'] }),
  K('K13', 'Wir hätten eine Katze mit Harnverhalt, könnt ihr die heute übernehmen?', { expectTriage: ['emergency'], must: ['sofort'], sev: 'unsafe' }),

  // ================= M. Bilder (Bildunterschrift läuft durch Triage + Anliegen) =================
  { id: 'I01', cat: 'image', image: true, text: '', must: ['Bild'], sev: 'wrong' },
  { id: 'I02', cat: 'image', image: true, text: 'Mein Hund blutet stark', expectTriage: ['emergency'], must: ['^.{0,120}(sofort|anrufen)', 'Bild'], sev: 'unsafe' },
  { id: 'I03', cat: 'image', image: true, text: 'Ist das eine Zecke?', must: ['Bild', '(Zecke|Floh|Parasit|Spot|Wurm|Präparat|Mittel)'], sev: 'unhelpful' },
  { id: 'I04', cat: 'image', image: true, persona: 'colleague', text: 'Röntgenbild von heute', must: ['Bild'], mustNot: [OWNERISH], sev: 'wrong' },
];
