/* data.jsx — i18n strings + course content (Austria/EU law, educational demo) */

// translate helper: t({de,en}, lang)
function T(o, lang){ if(o==null) return ''; if(typeof o==='string') return o; return o[lang] ?? o.de ?? ''; }
window.T = T;

// ---- UI strings ----
const STR = {
  appName:{de:'Avocado at Law', en:'Avocado at Law'},
  disclaimer:{de:'Demo – keine Rechtsberatung', en:'Demo – not legal advice'},
  getStarted:{de:'LOS GEHT\u2019S', en:'GET STARTED'},
  haveAccount:{de:'ICH HABE BEREITS EIN KONTO', en:'I ALREADY HAVE AN ACCOUNT'},
  continue:{de:'WEITER', en:'CONTINUE'},
  check:{de:'\u00DCBERPR\u00DCFEN', en:'CHECK'},
  cont2:{de:'WEITER', en:'CONTINUE'},
  cantAnswer:{de:'ICH WEISS ES NICHT', en:'SKIP'},
  correct:{de:'Richtig!', en:'Correct!'},
  niceWork:{de:'Stark!', en:'Nice work!'},
  wrong:{de:'Nicht ganz \u2026', en:'Not quite \u2026'},
  answerWas:{de:'Richtige Antwort:', en:'Correct answer:'},
  lessonDone:{de:'Lektion gemeistert!', en:'Lesson complete!'},
  totalXp:{de:'GESAMT-XP', en:'TOTAL XP'},
  amazing:{de:'Pl\u00E4doyer gewonnen!', en:'Case won!'},
  committed:{de:'ICH BIN DABEI', en:'I\u2019M COMMITTED'},
  claim:{de:'ABHOLEN', en:'CLAIM'},
  tabLearn:{de:'Lernen', en:'Learn'},
  tabLeague:{de:'Liga', en:'League'},
  tabProfile:{de:'Profil', en:'Profile'},
  start:{de:'STARTEN', en:'START'},
  review:{de:'WIEDERHOLEN', en:'REVIEW'},
  locked:{de:'Gesperrt', en:'Locked'},
  jumpHere:{de:'HIERHIN SPRINGEN', en:'JUMP HERE'},
  moreSoon:{de:'Mehr Lektionen kommen bald!', en:'More lessons coming soon!'},
  unit:{de:'ABSCHNITT', en:'SECTION'},
  streakTitle:{de:'Tage-Streak', en:'day streak'},
  streakSub:{de:'Lerne jeden Tag, um deinen Streak zu halten!', en:'Practice every day to keep your streak!'},
  keepFire:{de:'FEUER AM LEBEN HALTEN', en:'KEEP MY FIRE ALIVE'},
  dailyGoalQ:{de:'Was ist dein t\u00E4gliches Lernziel?', en:'What\u2019s your daily goal?'},
  whyQ:{de:'Warum lernst du Recht?', en:'Why are you learning law?'},
  hearQ:{de:'Wie hast du von uns geh\u00F6rt?', en:'How did you hear about us?'},
  langQ:{de:'Was m\u00F6chtest du lernen?', en:'What would you like to learn?'},
  startWhereQ:{de:'Wo m\u00F6chtest du starten?', en:'Where would you like to start?'},
  knowQ:{de:'Wie gut kennst du dich mit deinen Rechten aus?', en:'How well do you know your rights?'},
  league:{de:'Avocado-Liga', en:'Avocado League'},
  leagueSub:{de:'Top 3 steigen auf \u2022 endet in 4 Tagen', en:'Top 3 advance \u2022 ends in 4 days'},
  profileEdit:{de:'Profil bearbeiten', en:'Edit profile'},
  statistics:{de:'Statistik', en:'Statistics'},
  dayStreak:{de:'Tage-Streak', en:'Day streak'},
  totalXpStat:{de:'Gesamt-XP', en:'Total XP'},
  leagueStat:{de:'Liga', en:'League'},
  top3:{de:'Top-3-Pl\u00E4tze', en:'Top 3 finishes'},
  achievements:{de:'Erfolge', en:'Achievements'},
  member:{de:'Mitglied seit Juni 2026', en:'Member since June 2026'},
  hi:{de:'Hallo! Ich bin Avo,\ndein Rechts-Buddy.', en:'Hi! I\u2019m Avo,\nyour rights buddy.'},
  quick:{de:'Nur ein paar kurze Fragen,\nbevor wir loslegen!', en:'Just a few quick questions\nbefore we start!'},
  reminder:{de:'Ich erinnere dich, damit\nLernen zur Gewohnheit wird.', en:'I\u2019ll remind you so it\nbecomes a habit.'},
  fresh:{de:'Alles klar, wir\nstarten frisch!', en:'Okay, we\u2019ll\nstart fresh!'},
  goalReached:{de:'Tagesziel erreicht!', en:'Daily goal reached!'},
  // login
  loginTitle:{de:'Willkommen zur\u00FCck!', en:'Welcome back!'},
  loginSub:{de:'Melde dich an, um weiterzulernen.', en:'Sign in to keep learning.'},
  emailLabel:{de:'E-Mail', en:'Email'},
  pwLabel:{de:'Passwort', en:'Password'},
  forgotPw:{de:'Passwort vergessen?', en:'Forgot password?'},
  signIn:{de:'EINLOGGEN', en:'SIGN IN'},
  orWith:{de:'oder weiter mit', en:'or continue with'},
  noAccount:{de:'Noch kein Konto? Registrieren', en:'No account yet? Sign up'},
  // placement
  placeTitle:{de:'Kurzer Einstufungstest', en:'Quick placement test'},
  placeSub:{de:'Ein paar Fragen, damit Avo dich richtig platziert.', en:'A few questions so Avo can place you right.'},
  placeStart:{de:'TEST STARTEN', en:'START TEST'},
  placeDoneTitle:{de:'Dein Startpunkt steht!', en:'Your start point is set!'},
  // gems on complete
  gemsLabel:{de:'GEMS', en:'GEMS'},
  bonus:{de:'Bonus', en:'Bonus'},
  // hearts empty
  noHeartsTitle:{de:'Keine Herzen mehr!', en:'You\u2019re out of hearts!'},
  noHeartsBody:{de:'Avo dr\u00FCckt dir die Daumen \u2013 f\u00FClle deine Herzen auf oder versuche es sp\u00E4ter noch einmal.', en:'Avo\u2019s rooting for you \u2013 refill your hearts or try again later.'},
  refillHearts:{de:'HERZEN AUFF\u00DCLLEN', en:'REFILL HEARTS'},
  quitLesson:{de:'LEKTION VERLASSEN', en:'QUIT LESSON'},
  // streak milestone
  nextMilestone:{de:'N\u00E4chster Meilenstein', en:'Next milestone'},
  milestoneDays:{de:'Tage', en:'days'},
  milestoneReward:{de:'+40 Gems warten auf dich', en:'+40 gems waiting for you'},
  // settings
  settings:{de:'Einstellungen', en:'Settings'},
  secAppearance:{de:'Aussehen', en:'Appearance'},
  secLearning:{de:'Lernen', en:'Learning'},
  secAccount:{de:'Konto', en:'Account'},
  setStyle:{de:'Design-Stil', en:'Design style'},
  setDark:{de:'Dunkel-Modus', en:'Dark mode'},
  setAccent:{de:'Akzentfarbe', en:'Accent colour'},
  setFont:{de:'Schrift', en:'Font'},
  setMascot:{de:'Avo-Stil', en:'Avo style'},
  setGoal:{de:'T\u00E4gliches XP-Ziel', en:'Daily XP goal'},
  setReminders:{de:'Erinnerungen', en:'Reminders'},
  setSound:{de:'Soundeffekte', en:'Sound effects'},
  setLang:{de:'Sprache', en:'Language'},
  setName:{de:'Name', en:'Name'},
  setUser:{de:'Benutzername', en:'Username'},
  setReset:{de:'FORTSCHRITT ZUR\u00DCCKSETZEN', en:'RESET PROGRESS'},
  setResetSure:{de:'Wirklich alles zur\u00FCcksetzen?', en:'Really reset everything?'},
  yes:{de:'JA, ZUR\u00DCCKSETZEN', en:'YES, RESET'},
  no:{de:'ABBRECHEN', en:'CANCEL'},
  saved:{de:'Gespeichert!', en:'Saved!'},
  // daily goal card
  dailyGoal:{de:'Tagesziel', en:'Daily goal'},
  xpToday:{de:'XP heute', en:'XP today'},
  goalDone:{de:'Tagesziel geschafft! \uD83C\uDF89', en:'Daily goal reached! \uD83C\uDF89'},
  // exercise types
  orderPrompt:{de:'Bringe die Schritte in die richtige Reihenfolge.', en:'Put the steps in the right order.'},
  casePill:{de:'DER FALL', en:'THE CASE'},
};
window.STR = STR;

// onboarding option sets
const ONB = {
  langs:[
    {de:'Konsumentenrecht', en:'Consumer law', flag:'\uD83D\uDED2'},
    {de:'Arbeitsrecht', en:'Employment law', flag:'\uD83D\uDCBC'},
    {de:'Mietrecht', en:'Tenancy law', flag:'\uD83C\uDFE0'},
    {de:'Digitale Rechte', en:'Digital rights', flag:'\uD83D\uDCF1'},
  ],
  why:[
    {de:'Meine Rechte kennen', en:'Know my rights', emoji:'\u2696\uFE0F'},
    {de:'F\u00FCr Schule / Studium', en:'For school / studies', emoji:'\uD83D\uDCDA'},
    {de:'Beruflich weiterkommen', en:'Boost my career', emoji:'\uD83D\uDCBC'},
    {de:'Einfach interessiert', en:'Just curious', emoji:'\uD83E\uDDE0'},
    {de:'Streit clever l\u00F6sen', en:'Settle disputes smartly', emoji:'\uD83E\uDD1D'},
  ],
  hear:[
    {de:'TikTok', en:'TikTok'},{de:'Freunde / Familie', en:'Friends / family'},
    {de:'Google-Suche', en:'Google Search'},{de:'Instagram', en:'Instagram'},
    {de:'App Store', en:'App store'},{de:'News / Blog', en:'News / blog'},
  ],
  goals:[
    {de:'3 min / Tag', en:'3 min / day', tag:{de:'L\u00E4ssig', en:'Casual'}},
    {de:'10 min / Tag', en:'10 min / day', tag:{de:'Normal', en:'Regular'}},
    {de:'15 min / Tag', en:'15 min / day', tag:{de:'Ernst', en:'Serious'}},
    {de:'30 min / Tag', en:'30 min / day', tag:{de:'Intensiv', en:'Intense'}},
  ],
  know:[
    {de:'Ich fange bei Null an', en:'I\u2019m starting from zero', lvl:1},
    {de:'Ein paar Grundlagen', en:'A few basics', lvl:2},
    {de:'Ganz solide', en:'Pretty solid', lvl:3},
    {de:'Fast wie ein Profi', en:'Almost a pro', lvl:4},
  ],
  achieve3:[
    {de:'Deine Rechte sicher kennen', en:'Know your rights with confidence', sub:{de:'Alltagsrecht ohne Angst', en:'Everyday law, stress-free'}, c:'#CE82FF'},
    {de:'Vertr\u00E4ge verstehen', en:'Understand contracts', sub:{de:'Klauseln & Fristen lesen', en:'Read clauses & deadlines'}, c:'#1CB0F6'},
    {de:'Eine Lern-Gewohnheit', en:'Build a learning habit', sub:{de:'Kleine Schritte, jeden Tag', en:'Small steps, every day'}, c:'#FF9600'},
  ],
};
window.ONB = ONB;

// ---- helper builders ----
const mc = (q,options,answer,extra={}) => ({type:'mc', q, options, answer, ...extra});
const tf = (statement,answer,explain) => ({type:'tf', statement, answer, explain});
const gap = (parts,options,answer,extra={}) => ({type:'gap', parts, options, answer, ...extra});
const match = (q,pairs) => ({type:'match', q, pairs});
const build = (q,answer,bank,extra={}) => ({type:'build', q, answer, bank, ...extra});
const info = (text,mood='happy') => ({type:'info', text, mood});
const order = (q,steps) => ({type:'order', q, steps}); // steps in correct order
const caseMc = (scene,q,options,answer,extra={}) => ({type:'mc', scene, q, options, answer, ...extra}); // Brilliant-style case

// ---- COURSE ----
const COURSE = [
  {
    id:'u1', color:'#58CC02', icon:'\uD83D\uDED2',
    title:{de:'Konsumentenschutz', en:'Consumer protection'},
    blurb:{de:'Deine Rechte beim Einkaufen', en:'Your rights when you shop'},
    lessons:[
      { id:'u1l1', xp:20, title:{de:'Online-Kauf & R\u00FCcktritt', en:'Online buying & returns'}, exercises:[
        info({de:'Bei Online-K\u00E4ufen hast du in der EU 14 Tage Zeit, um ohne Angabe von Gr\u00FCnden zur\u00FCckzutreten.', en:'For online purchases in the EU you have 14 days to withdraw \u2014 no reason needed.'}, 'wave'),
        mc({de:'Du kaufst online Sneaker. Wie viele Tage hast du in der EU, um ohne Grund zur\u00FCckzutreten?', en:'You buy sneakers online. How many days do you have in the EU to withdraw without a reason?'},
           [{de:'7 Tage', en:'7 days'},{de:'14 Tage', en:'14 days'},{de:'30 Tage', en:'30 days'},{de:'Gar keine', en:'None'}], 1),
        tf({de:'Im Gesch\u00E4ft vor Ort gilt automatisch dasselbe 14-t\u00E4gige R\u00FCcktrittsrecht wie online.', en:'A physical shop automatically gives you the same 14-day withdrawal right as online.'},
           false, {de:'Im Laden gibt es kein gesetzliches R\u00FCcktrittsrecht \u2013 Umtausch ist reine Kulanz.', en:'Shops have no legal withdrawal right \u2013 returns are goodwill only.'}),
        mc({de:'Eine \u201EGarantie\u201C des Herstellers ist \u2026', en:'A manufacturer\u2019s \u201Cguarantee\u201D is \u2026'},
           [{de:'gesetzlich verpflichtend', en:'required by law'},{de:'eine freiwillige Zusage', en:'a voluntary promise'},{de:'nur 14 Tage g\u00FCltig', en:'valid only 14 days'},{de:'dasselbe wie Gew\u00E4hrleistung', en:'the same as warranty'}], 1,
           {hint:{de:'Tipp: Sie kommt zus\u00E4tzlich zur gesetzlichen Gew\u00E4hrleistung.', en:'Hint: it comes on top of the legal warranty.'}}),
        gap({de:'Die gesetzliche Gew\u00E4hrleistung betr\u00E4gt in \u00D6sterreich bei Neuware ___ Jahre.', en:'Legal warranty on new goods in Austria lasts ___ years.'},
           [{de:'1', en:'1'},{de:'2', en:'2'},{de:'5', en:'5'}], 1),
        match({de:'Ordne die Begriffe richtig zu.', en:'Match the terms.'},
           [{a:{de:'Gew\u00E4hrleistung', en:'Warranty'}, b:{de:'gesetzlich, 2 Jahre', en:'by law, 2 years'}},
            {a:{de:'Garantie', en:'Guarantee'}, b:{de:'freiwillig', en:'voluntary'}},
            {a:{de:'R\u00FCcktritt', en:'Withdrawal'}, b:{de:'14 Tage online', en:'14 days online'}},
            {a:{de:'Mangel', en:'Defect'}, b:{de:'Ware ist fehlerhaft', en:'item is faulty'}}]),
        build({de:'Bau den Satz: \u201EEin Online-Kauf kann innerhalb von 14 Tagen widerrufen werden.\u201C', en:'Build: \u201CAn online purchase can be withdrawn within 14 days.\u201C'},
           {de:['Ein','Online-Kauf','kann','innerhalb','von','14','Tagen','widerrufen','werden'], en:['An','online','purchase','can','be','withdrawn','within','14','days']},
           {de:['Ein','Tagen','Online-Kauf','von','widerrufen','kann','14','werden','innerhalb','Wochen'], en:['An','days','online','within','withdrawn','can','14','be','purchase','weeks']}),
        mc({de:'Ab wann läuft die 14-tägige Rücktrittsfrist bei Waren?', en:'When does the 14-day withdrawal period start for goods?'},
           [{de:'Ab Bestellung', en:'From ordering'},{de:'Ab Erhalt der Ware', en:'From receiving the goods'},{de:'Ab Bezahlung', en:'From payment'},{de:'Ab Versand', en:'From shipping'}], 1,
           {hint:{de:'Bei Waren zählt der Tag, an dem du das Paket bekommst.', en:'For goods it starts the day the parcel arrives.'}}),
        tf({de:'Auch ein individuell angefertigtes Produkt (z.B. mit Gravur) kannst du immer in 14 Tagen zurückgeben.', en:'A custom-made product (e.g. engraved) can always be returned within 14 days, too.'},
           false, {de:'Maßanfertigungen sind vom Rücktrittsrecht meist ausgenommen.', en:'Tailor-made items are usually excluded from the withdrawal right.'}),
      ]},
      { id:'u1l2', xp:20, title:{de:'Gew\u00E4hrleistung', en:'Warranty & defects'}, exercises:[
        info({de:'Ist die Ware von Anfang an kaputt, hast du Recht auf Reparatur oder Austausch.', en:'If an item is faulty from the start, you\u2019re entitled to repair or replacement.'}),
        mc({de:'Dein neues Handy hat nach 3 Wochen einen Defekt. Wer muss zuerst beweisen, ob der Mangel von Anfang an bestand?', en:'Your new phone breaks after 3 weeks. Who must prove whether the defect existed from the start?'},
           [{de:'Du als K\u00E4ufer:in', en:'You, the buyer'},{de:'Der/die Verk\u00E4ufer:in', en:'The seller'},{de:'Niemand', en:'Nobody'},{de:'Der Hersteller', en:'The maker'}], 1,
           {hint:{de:'Im ersten Jahr wird vermutet, dass der Mangel schon bei \u00DCbergabe bestand.', en:'In the first year the defect is presumed to have existed at handover.'}}),
        tf({de:'Bei einem Mangel darf der/die Verk\u00E4ufer:in dich sofort an den Hersteller verweisen.', en:'For a defect, the seller may simply send you to the manufacturer.'},
           false, {de:'Dein Vertragspartner ist der/die Verk\u00E4ufer:in \u2013 dort machst du Gew\u00E4hrleistung geltend.', en:'Your contract is with the seller \u2013 claim the warranty there.'}),
        gap({de:'Im ersten Jahr nach dem Kauf gilt die ___ : Der Mangel wird als von Anfang an vermutet.', en:'In the first year, the ___ applies: the defect is presumed to be original.'},
           [{de:'Beweislastumkehr', en:'reversed burden of proof'},{de:'K\u00FCndigung', en:'termination'},{de:'Mahnung', en:'reminder'}], 0),
        mc({de:'Die Ware ist mangelhaft. Was kannst du zuerst verlangen?', en:'The item is defective. What can you ask for first?'},
           [{de:'Reparatur oder Austausch', en:'Repair or replacement'},{de:'Sofort Geld zur\u00FCck', en:'An instant refund'},{de:'Eine Entschuldigung', en:'An apology'},{de:'Einen Gutschein', en:'A voucher'}], 0),
        build({de:'Bau den Satz: \u201EDie Ware war von Anfang an mangelhaft.\u201C', en:'Build: \u201CThe item was defective from the start.\u201C'},
           {de:['Die','Ware','war','von','Anfang','an','mangelhaft'], en:['The','item','was','defective','from','the','start']},
           {de:['Ware','Anfang','Die','an','war','neu','von','mangelhaft'], en:['item','from','The','defective','was','new','the','start']}),
      ]},
      { id:'u1l3', xp:20, title:{de:'Online-Abos & Fallen', en:'Subscriptions & traps'}, exercises:[
        info({de:'Eine Abo-Falle versteckt Kosten im Kleingedruckten. In der EU braucht ein kostenpflichtiger Button eine klare Beschriftung wie „zahlungspflichtig bestellen“.', en:'A subscription trap hides costs in the fine print. In the EU a paid button must be clearly labelled, e.g. “order with obligation to pay”.'}, 'fire'),
        mc({de:'Ein Gratis-Test wird nach 7 Tagen automatisch zum teuren Abo. Was gilt in der EU?', en:'A free trial auto-converts to a costly subscription after 7 days. What applies in the EU?'},
           [{de:'Die Kostenfolge muss vorher klar genannt sein', en:'The cost must be clearly stated up front'},{de:'Schweigen zählt als Zustimmung', en:'Silence counts as consent'},{de:'Abos sind immer 24 Monate fix', en:'Subscriptions are always fixed for 24 months'},{de:'Nichts – Pech gehabt', en:'Nothing – tough luck'}], 0),
        tf({de:'Ein Online-Abo muss sich so leicht kündigen lassen, wie man es abgeschlossen hat.', en:'An online subscription must be as easy to cancel as it was to start.'},
           true, {de:'Der „Kündigungsbutton“ ist in der EU Pflicht – kein Hindernislauf erlaubt.', en:'A clear “cancel button” is required in the EU – no obstacle course allowed.'}),
        gap({de:'Versteckte Kosten ohne klare Zustimmung musst du ___ zahlen.', en:'Hidden costs without clear consent you have to pay ___.'},
           [{de:'nicht', en:'not'},{de:'sofort', en:'at once'},{de:'doppelt', en:'double'}], 0),
      ]},
      { id:'u1l4', xp:30, title:{de:'Reklamation richtig', en:'Complaining the right way'}, exercises:[
        info({de:'Bei einem Mangel reklamierst du am besten schriftlich – mit Datum, Fehlerbeschreibung und einer Frist zur Behebung.', en:'For a defect, complain in writing – with the date, a description of the fault and a deadline to fix it.'}),
        mc({de:'Was gehört NICHT in eine gute schriftliche Reklamation?', en:'What does NOT belong in a good written complaint?'},
           [{de:'Kaufdatum & Beleg', en:'Date of purchase & receipt'},{de:'Beschreibung des Mangels', en:'Description of the defect'},{de:'Eine angemessene Frist', en:'A reasonable deadline'},{de:'Beleidigungen', en:'Insults'}], 3),
        tf({de:'Du musst dem/der Verkäufer:in eine angemessene Frist zur Reparatur oder zum Austausch geben.', en:'You must give the seller a reasonable deadline to repair or replace.'},
           true, {de:'Erst nach erfolglosem Fristablauf kannst du Preis mindern oder vom Vertrag zurücktreten.', en:'Only after the deadline passes can you reduce the price or withdraw.'}),
        build({de:'Bau den Satz: „Ich fordere Sie auf, den Mangel zu beheben.“', en:'Build: “I request that you fix the defect.”'},
           {de:['Ich','fordere','Sie','auf','den','Mangel','zu','beheben'], en:['I','request','that','you','fix','the','defect']},
           {de:['Ich','Mangel','fordere','beheben','Sie','den','auf','zu','sofort'], en:['I','defect','request','fix','that','the','you','now']}),
      ]},
    ],
  },
  {
    id:'u2', color:'#1CB0F6', icon:'\uD83D\uDCBC',
    title:{de:'Dein erster Job', en:'Your first job'},
    blurb:{de:'Arbeitsvertrag, Urlaub & Lohn', en:'Contracts, leave & pay'},
    lessons:[
      { id:'u2l1', xp:20, title:{de:'Der Arbeitsvertrag', en:'The work contract'}, exercises:[
        info({de:'Ein Arbeitsvertrag kann m\u00FCndlich gelten \u2013 doch du hast Anspruch auf einen schriftlichen Dienstzettel.', en:'A work contract can be verbal \u2013 but you\u2019re entitled to a written statement of terms.'}, 'wave'),
        mc({de:'Wie lange darf die Probezeit in \u00D6sterreich h\u00F6chstens dauern?', en:'How long may a probation period last in Austria at most?'},
           [{de:'1 Monat', en:'1 month'},{de:'3 Monate', en:'3 months'},{de:'6 Monate', en:'6 months'},{de:'1 Jahr', en:'1 year'}], 0,
           {hint:{de:'In \u00D6sterreich gilt meist der \u201EProbemonat\u201C.', en:'Austria usually allows a one-month trial.'}}),
        gap({de:'Der gesetzliche Mindesturlaub betr\u00E4gt in \u00D6sterreich ___ Wochen pro Jahr.', en:'Statutory minimum holiday in Austria is ___ weeks per year.'},
           [{de:'2', en:'2'},{de:'5', en:'5'},{de:'8', en:'8'}], 1),
        tf({de:'In \u00D6sterreich legt der Staat einen einheitlichen gesetzlichen Mindestlohn fest.', en:'In Austria the state sets one nationwide statutory minimum wage.'},
           false, {de:'In \u00D6sterreich regeln das die Kollektivvertr\u00E4ge der jeweiligen Branche.', en:'In Austria, sector collective agreements set minimum pay.'}),
        match({de:'Ordne die Begriffe zu.', en:'Match the terms.'},
           [{a:{de:'Dienstzettel', en:'Statement of terms'}, b:{de:'schriftliche Eckdaten', en:'written key facts'}},
            {a:{de:'Kollektivvertrag', en:'Collective agr.'}, b:{de:'Mindestlohn der Branche', en:'sector minimum pay'}},
            {a:{de:'Probezeit', en:'Probation'}, b:{de:'max. 1 Monat', en:'max. 1 month'}}]),
        mc({de:'Dein:e Chef:in will den Urlaub einseitig bestimmen. Geht das?', en:'Your boss wants to set your holiday unilaterally. Allowed?'},
           [{de:'Nein, Urlaub wird vereinbart', en:'No, holiday is agreed together'},{de:'Ja, immer', en:'Yes, always'},{de:'Nur im Winter', en:'Only in winter'},{de:'Nur für Lehrlinge', en:'Only for apprentices'}], 0,
           {hint:{de:'Der Urlaubszeitpunkt wird zwischen beiden Seiten vereinbart.', en:'The timing of leave is agreed between both sides.'}}),
        tf({de:'Während der Probezeit kann das Arbeitsverhältnis von beiden Seiten jederzeit gelöst werden.', en:'During probation either side may end the job at any time.'},
           true, {de:'In der Probezeit braucht es weder Frist noch Grund – das gilt für beide.', en:'In probation no notice or reason is needed – for either side.'}),
      ]},
      { id:'u2l2', xp:20, title:{de:'K\u00FCndigung & Fristen', en:'Notice & deadlines'}, exercises:[
        info({de:'Eine K\u00FCndigung beendet das Arbeitsverh\u00E4ltnis. Dabei gelten Fristen \u2013 sie sch\u00FCtzen beide Seiten vor einem zu pl\u00F6tzlichen Ende.', en:'A termination ends the job. Notice periods apply \u2013 they protect both sides from too sudden an end.'}, 'wave'),
        mc({de:'Was ist der Unterschied zwischen K\u00FCndigung und Entlassung?', en:'What is the difference between ordinary notice and summary dismissal?'},
           [{de:'Entlassung erfolgt fristlos aus wichtigem Grund', en:'Dismissal is immediate, for serious cause'},{de:'Es gibt keinen Unterschied', en:'There is no difference'},{de:'K\u00FCndigung ist immer sofort', en:'Notice always means immediately'},{de:'Entlassung gilt nur f\u00FCr Chefs', en:'Dismissal is only for bosses'}], 0,
           {hint:{de:'Fristlos = sofort, aber nur bei schwerem Fehlverhalten.', en:'Summary = immediate, but only for serious misconduct.'}}),
        tf({de:'Auch w\u00E4hrend des Krankenstands kann grunds\u00E4tzlich gek\u00FCndigt werden.', en:'You can in principle be given notice even while on sick leave.'},
           true, {de:'Der Entgeltanspruch im Krankenstand bleibt aber meist bestehen.', en:'But your sick-pay entitlement usually continues.'}),
        gap({de:'Eine schriftliche K\u00FCndigung sollte immer ein ___ tragen.', en:'A written notice should always carry a ___.'},
           [{de:'Datum', en:'date'},{de:'Foto', en:'photo'},{de:'Siegel', en:'seal'}], 0),
      ]},
      { id:'u2l3', xp:30, title:{de:'Lohnzettel lesen', en:'Reading your payslip'}, exercises:[
        info({de:'Auf dem Lohnzettel steht oben das Brutto, unten das Netto. Dazwischen liegen Steuern und Sozialversicherung.', en:'A payslip shows gross at the top and net at the bottom. In between sit taxes and social insurance.'}),
        mc({de:'Was bekommst du tats\u00E4chlich aufs Konto?', en:'What actually lands in your bank account?'},
           [{de:'Das Brutto', en:'The gross'},{de:'Das Netto', en:'The net'},{de:'Brutto plus Steuer', en:'Gross plus tax'},{de:'Die Lohnsteuer', en:'The wage tax'}], 1),
        match({de:'Ordne die Begriffe vom Lohnzettel zu.', en:'Match the payslip terms.'},
           [{a:{de:'Brutto', en:'Gross'}, b:{de:'vor Abz\u00FCgen', en:'before deductions'}},
            {a:{de:'Netto', en:'Net'}, b:{de:'was bleibt', en:'what remains'}},
            {a:{de:'SV-Beitrag', en:'Social insurance'}, b:{de:'Kranken & Pension', en:'health & pension'}},
            {a:{de:'Lohnsteuer', en:'Wage tax'}, b:{de:'an das Finanzamt', en:'to the tax office'}}]),
        tf({de:'Das 13. und 14. Gehalt (Urlaubs- & Weihnachtsgeld) ist in \u00D6sterreich steuerlich beg\u00FCnstigt.', en:'The 13th & 14th salary (holiday & Christmas pay) is tax-privileged in Austria.'},
           true, {de:'Diese Sonderzahlungen werden mit nur 6 % besteuert \u2013 das \u201EJahressechstel\u201C.', en:'These special payments are taxed at just 6 % \u2013 the \u201Cannual sixth\u201D.'}),
      ]},
    ],
  },
  {
    id:'u3', color:'#CE82FF', icon:'\uD83D\uDCF1',
    title:{de:'Handy & Internet', en:'Phone & internet'},
    blurb:{de:'Vertr\u00E4ge, Roaming & Daten', en:'Contracts, roaming & data'},
    lessons:[
      { id:'u3l1', xp:20, title:{de:'Mobilfunkvertrag', en:'Mobile contracts'}, exercises:[
        info({de:'Seit 2017 gilt in der EU \u201ERoam like at home\u201C: Telefonieren und Surfen im EU-Ausland kostet nichts extra.', en:'Since 2017 the EU rule \u201CRoam like at home\u201C means no extra roaming fees within the EU.'}, 'celebrate'),
        mc({de:'Du f\u00E4hrst nach Italien. Was kostet dein normales Datenvolumen dort laut EU-Roaming-Regel?', en:'You travel to Italy. What does your normal data cost there under EU roaming rules?'},
           [{de:'Doppelt so viel', en:'Double'},{de:'Nichts extra', en:'Nothing extra'},{de:'Pro MB Aufpreis', en:'A fee per MB'},{de:'Nur mit WLAN', en:'Wi-Fi only'}], 1),
        tf({de:'Ein Mobilfunkvertrag darf dich unbegrenzt lange binden, z.B. 5 Jahre.', en:'A mobile contract may lock you in indefinitely, e.g. 5 years.'},
           false, {de:'In der EU sind h\u00F6chstens 24 Monate Bindung erlaubt \u2013 eine Option bis 12 Monate muss es geben.', en:'In the EU max lock-in is 24 months \u2013 a \u226412-month option must be offered.'}),
        gap({de:'Beim Anbieterwechsel darfst du deine ___ mitnehmen.', en:'When you switch providers, you may keep your ___.'},
           [{de:'Rufnummer', en:'phone number'},{de:'SIM-Gr\u00F6\u00DFe', en:'SIM size'},{de:'IMEI', en:'IMEI'}], 0),
        mc({de:'Dein Vertrag verl\u00E4ngert sich automatisch. Was gilt heute in der EU?', en:'Your contract auto-renews. What applies in the EU today?'},
           [{de:'Du kannst danach monatlich k\u00FCndigen', en:'You can then cancel monthly'},{de:'Du steckst 2 weitere Jahre fest', en:'You\u2019re stuck for 2 more years'},{de:'Die K\u00FCndigung ist unm\u00F6glich', en:'Cancelling is impossible'},{de:'Der Preis verdoppelt sich', en:'The price doubles'}], 0),
      ]},
      { id:'u3l2', xp:30, title:{de:'Datenschutz & DSGVO', en:'Privacy & GDPR'}, exercises:[
        info({de:'Die DSGVO gibt dir Rechte über deine Daten: Auskunft, Berichtigung und Löschung – das „Recht auf Vergessenwerden“.', en:'The GDPR gives you rights over your data: access, correction and erasure – the “right to be forgotten”.'}, 'celebrate'),
        mc({de:'Eine App will auf deine Kontakte zugreifen. Was muss sie zuerst einholen?', en:'An app wants access to your contacts. What must it obtain first?'},
           [{de:'Deine ausdrückliche Einwilligung', en:'Your explicit consent'},{de:'Nur eine E-Mail', en:'Just an email'},{de:'Gar nichts', en:'Nothing'},{de:'Die Zustimmung der Eltern', en:'Your parents’ consent'}], 0),
        tf({de:'Du darfst von einem Unternehmen verlangen, dass es alle deine Daten löscht.', en:'You may ask a company to delete all your data.'},
           true, {de:'Das „Recht auf Löschung“ gilt – sofern keine gesetzliche Aufbewahrungspflicht entgegensteht.', en:'The “right to erasure” applies – unless a legal retention duty stands in the way.'}),
        gap({de:'Auf eine Datenauskunft muss ein Unternehmen grundsätzlich innerhalb eines ___ reagieren.', en:'A company must answer a data-access request within one ___.'},
           [{de:'Monats', en:'month'},{de:'Jahres', en:'year'},{de:'Tages', en:'day'}], 0),
      ]},
      { id:'u3l3', xp:30, title:{de:'Betrug & Phishing', en:'Scams & phishing'}, exercises:[
        info({de:'Phishing-Nachrichten täuschen Banken oder Paketdienste vor, um an Passwörter zu kommen. Echte Stellen fragen nie per Link nach deinem Passwort.', en:'Phishing messages pretend to be banks or delivery firms to steal passwords. Real institutions never ask for your password via a link.'}, 'fire'),
        mc({de:'Eine SMS: „Ihr Paket wartet, zahlen Sie 2€: bit.ly/xy“. Was tust du?', en:'A text: “Your parcel is waiting, pay €2: bit.ly/xy“. What do you do?'},
           [{de:'Nicht klicken, löschen', en:'Don’t click, delete it'},{de:'Sofort zahlen', en:'Pay at once'},{de:'Kreditkarte eingeben', en:'Enter my card'},{de:'Zurückschreiben', en:'Reply to it'}], 0),
        tf({de:'Deine Bank wird dich nie per Link auffordern, dein Passwort einzugeben.', en:'Your bank will never ask you to enter your password via a link.'},
           true, {de:'Bei Zweifel: Seite selbst im Browser öffnen, nie dem Link folgen.', en:'When in doubt: open the site yourself, never follow the link.'}),
        gap({de:'Schutz vor Konto-Diebstahl bietet die ___-Faktor-Authentifizierung.', en:'Protection against account theft comes from ___-factor authentication.'},
           [{de:'Zwei', en:'Two'},{de:'Null', en:'Zero'},{de:'Halb', en:'Half'}], 0),
        build({de:'Bau den Satz: „Ich gebe mein Passwort niemals weiter.“', en:'Build: “I never share my password.“'},
           {de:['Ich','gebe','mein','Passwort','niemals','weiter'], en:['I','never','share','my','password']},
           {de:['Passwort','Ich','niemals','mein','weiter','gebe','immer'], en:['share','I','password','my','never','always']}),
      ]},
    ],
  },
  {
    id:'u4', color:'#FF9600', icon:'\uD83C\uDFE0',
    title:{de:'Wohnen & Miete', en:'Housing & rent'},
    blurb:{de:'Mietvertrag, Kaution & Co.', en:'Leases, deposits & more'},
    lessons:[
      { id:'u4l1', xp:20, title:{de:'Kaution & Mietvertrag', en:'Deposit & lease'}, exercises:[
        info({de:'Die Kaution ist eine Sicherheit. Nach dem Auszug bekommst du sie zur\u00FCck \u2013 abz\u00FCglich berechtigter Forderungen.', en:'A deposit is security. After moving out you get it back \u2013 minus any justified claims.'}),
        mc({de:'Wie hoch ist die Kaution \u00FCblicherweise maximal?', en:'How high is a deposit usually capped?'},
           [{de:'1 Monatsmiete', en:'1 month\u2019s rent'},{de:'3 Monatsmieten', en:'3 months\u2019 rent'},{de:'1 Jahresmiete', en:'a year\u2019s rent'},{de:'Unbegrenzt', en:'Unlimited'}], 1,
           {hint:{de:'In der Regel maximal drei Bruttomonatsmieten.', en:'Usually capped at three gross monthly rents.'}}),
        tf({de:'Der/die Vermieter:in darf die Kaution behalten, auch wenn nichts besch\u00E4digt wurde.', en:'A landlord may keep the deposit even if nothing was damaged.'},
           false, {de:'Ohne offene Forderungen oder Sch\u00E4den musst du die volle Kaution zur\u00FCckbekommen.', en:'With no claims or damage, the full deposit must be returned.'}),
        gap({de:'Ein befristeter Hauptmietvertrag muss in \u00D6sterreich mindestens ___ Jahre dauern.', en:'A fixed-term main lease in Austria must last at least ___ years.'},
           [{de:'1', en:'1'},{de:'3', en:'3'},{de:'10', en:'10'}], 1),
        build({de:'Bau den Satz: \u201EDie Kaution wird nach dem Auszug zur\u00FCckgezahlt.\u201C', en:'Build: \u201CThe deposit is returned after you move out.\u201C'},
           {de:['Die','Kaution','wird','nach','dem','Auszug','zur\u00FCckgezahlt'], en:['The','deposit','is','returned','after','you','move','out']},
           {de:['Kaution','dem','Die','Auszug','wird','bezahlt','nach','zur\u00FCckgezahlt','vor'], en:['deposit','after','The','returned','is','paid','you','move','out','before']}),
        mc({de:'Dein:e Vermieter:in will die Kaution bar und ohne Beleg. Was tust du?', en:'Your landlord wants the deposit in cash with no receipt. What do you do?'},
           [{de:'Immer eine Best\u00E4tigung verlangen', en:'Always ask for a receipt'},{de:'Einfach zahlen', en:'Just pay it'},{de:'Doppelt zahlen', en:'Pay double'},{de:'Nichts unterschreiben und gehen', en:'Sign nothing and leave'}], 0,
           {hint:{de:'Ohne Beleg kannst du die Zahlung sp\u00E4ter kaum beweisen.', en:'Without a receipt you can hardly prove the payment later.'}}),
      ]},
      { id:'u4l2', xp:30, title:{de:'Betriebskosten', en:'Operating costs'}, exercises:[
        info({de:'Betriebskosten sind laufende Kosten rund ums Wohnen – Wasser, Müll, Grundsteuer. Sie kommen zur Miete dazu.', en:'Operating costs are the running costs of a home – water, refuse, property tax. They come on top of the rent.'}),
        mc({de:'Was zählt typischerweise NICHT zu den Betriebskosten?', en:'What does typically NOT count as an operating cost?'},
           [{de:'Wasser & Kanal', en:'Water & sewage'},{de:'Müllabfuhr', en:'Refuse collection'},{de:'Deine Stromrechnung', en:'Your electricity bill'},{de:'Grundsteuer', en:'Property tax'}], 2,
           {hint:{de:'Strom rechnest du meist direkt mit dem Anbieter ab.', en:'Electricity is usually billed directly by your provider.'}}),
        tf({de:'Der/die Vermieter:in muss einmal jährlich über die Betriebskosten abrechnen.', en:'The landlord must settle the operating costs once a year.'},
           true, {de:'Du hast Anspruch auf eine nachvollziehbare jährliche Abrechnung – und auf Belegeinsicht.', en:'You’re entitled to a clear annual statement – and to inspect the receipts.'}),
        gap({de:'Hast du zu viel gezahlt, bekommst du eine ___.', en:'If you paid too much, you get a ___.'},
           [{de:'Gutschrift', en:'refund'},{de:'Mahnung', en:'reminder'},{de:'Kündigung', en:'notice'}], 0),
      ]},
    ],
  },
  {
    id:'u5', color:'#FF5A4D', icon:'\uD83D\uDCB6',
    title:{de:'Geld & Vertr\u00E4ge', en:'Money & contracts'},
    blurb:{de:'Schulden, Mahnungen & Kleingedrucktes', en:'Debt, reminders & fine print'},
    lessons:[
      { id:'u5l1', xp:20, title:{de:'Eine Mahnung kommt', en:'A reminder arrives'}, exercises:[
        info({de:'Eine Mahnung ist eine Zahlungserinnerung. Erst nach Verzug d\u00FCrfen angemessene Mahnspesen dazukommen \u2013 keine Fantasiebetr\u00E4ge.', en:'A reminder asks you to pay. Only once you\u2019re in default may reasonable reminder fees be added \u2013 no fantasy amounts.'}, 'fire'),
        mc({de:'Du bekommst eine Mahnung mit 90 \u20AC \u201EBearbeitungsgeb\u00FChr\u201C f\u00FCr eine 20-\u20AC-Rechnung. Was gilt?', en:'You get a reminder with a \u20AC90 \u201Cprocessing fee\u201D for a \u20AC20 bill. What applies?'},
           [{de:'Spesen m\u00FCssen angemessen sein', en:'Fees must be proportionate'},{de:'Du musst alles sofort zahlen', en:'You must pay it all at once'},{de:'Mahnspesen sind immer verboten', en:'Reminder fees are always banned'},{de:'90 \u20AC sind v\u00F6llig normal', en:'\u20AC90 is totally normal'}], 0),
        tf({de:'Schon die erste Zahlungserinnerung darf hohe Inkassokosten enthalten.', en:'The very first payment reminder may already include high debt-collection costs.'},
           false, {de:'Erst bei tats\u00E4chlichem Verzug \u2013 und nur in angemessener H\u00F6he.', en:'Only once you\u2019re genuinely in default \u2013 and only in a reasonable amount.'}),
        gap({de:'Bevor du zahlst, pr\u00FCfst du immer, ob die Forderung \u00FCberhaupt ___ ist.', en:'Before paying, always check whether the claim is even ___.'},
           [{de:'berechtigt', en:'justified'},{de:'bunt', en:'colourful'},{de:'alt', en:'old'}], 0),
      ]},
      { id:'u5l2', xp:20, title:{de:'Vertrag unterschreiben', en:'Signing a contract'}, exercises:[
        info({de:'Eine Unterschrift bindet. Lies vor allem Laufzeit, K\u00FCndigung und versteckte Kosten \u2013 m\u00FCndliche Zusagen z\u00E4hlen sp\u00E4ter selten.', en:'A signature binds you. Read the term, cancellation and hidden costs above all \u2013 verbal promises rarely count later.'}),
        mc({de:'Was solltest du vor jeder Unterschrift checken?', en:'What should you check before every signature?'},
           [{de:'Laufzeit & K\u00FCndigungsfrist', en:'Term & notice period'},{de:'Die Schriftgr\u00F6\u00DFe', en:'The font size'},{de:'Die Papierfarbe', en:'The paper colour'},{de:'Gar nichts', en:'Nothing'}], 0),
        tf({de:'Ein an der Haust\u00FCr abgeschlossener Vertrag kann meist innerhalb von 14 Tagen widerrufen werden.', en:'A contract signed at your front door can usually be withdrawn within 14 days.'},
           true, {de:'F\u00FCr Haust\u00FCr- und Fern-Gesch\u00E4fte gilt ein 14-t\u00E4giges R\u00FCcktrittsrecht.', en:'Doorstep and distance deals carry a 14-day withdrawal right.'}),
        match({de:'Ordne die Vertrags-Begriffe zu.', en:'Match the contract terms.'},
           [{a:{de:'Laufzeit', en:'Term'}, b:{de:'wie lange es gilt', en:'how long it runs'}},
            {a:{de:'K\u00FCndigungsfrist', en:'Notice period'}, b:{de:'rechtzeitig aussteigen', en:'exit in time'}},
            {a:{de:'Widerruf', en:'Withdrawal'}, b:{de:'14 Tage zur\u00FCck', en:'14 days to undo'}}]),
      ]},
      { id:'u5l3', xp:30, title:{de:'B\u00FCrgschaft & Risiko', en:'Guarantees & risk'}, exercises:[
        info({de:'Wer b\u00FCrgt, haftet f\u00FCr fremde Schulden. Zahlt der/die Hauptschuldner:in nicht, kann die Bank sich an dich wenden.', en:'If you act as guarantor, you\u2019re liable for someone else\u2019s debt. If the main debtor doesn\u2019t pay, the bank can turn to you.'}, 'fire'),
        mc({de:'Ein:e Freund:in bittet dich, f\u00FCr einen Kredit zu b\u00FCrgen. Was bedeutet das f\u00FCr dich?', en:'A friend asks you to guarantee a loan. What does that mean for you?'},
           [{de:'Du haftest, wenn sie nicht zahlen', en:'You\u2019re liable if they don\u2019t pay'},{de:'Du bekommst Zinsen', en:'You earn interest'},{de:'Gar nichts', en:'Nothing at all'},{de:'Du wirst Mitbesitzer:in', en:'You become a co-owner'}], 0),
        tf({de:'Eine B\u00FCrgschaft solltest du nie unterschreiben, ohne die m\u00F6gliche Gesamtsumme zu kennen.', en:'You should never sign a guarantee without knowing the maximum amount.'},
           true, {de:'Kenne immer die H\u00F6chsthaftung \u2013 sie kann gr\u00F6\u00DFer sein als gedacht.', en:'Always know the maximum liability \u2013 it can be bigger than you think.'}),
        gap({de:'Bevor du b\u00FCrgst, pr\u00FCfst du, ob du die Summe im Notfall selbst ___ k\u00F6nntest.', en:'Before guaranteeing, check whether you could ___ the amount yourself if needed.'},
           [{de:'zahlen', en:'pay'},{de:'vergessen', en:'forget'},{de:'verschenken', en:'gift'}], 0),
        match({de:'Ordne die Begriffe zu.', en:'Match the terms.'},
           [{a:{de:'B\u00FCrge', en:'Guarantor'}, b:{de:'haftet f\u00FCr andere', en:'liable for others'}},
            {a:{de:'Hauptschuldner', en:'Main debtor'}, b:{de:'schuldet zuerst', en:'owes first'}},
            {a:{de:'H\u00F6chsthaftung', en:'Max liability'}, b:{de:'Obergrenze', en:'upper limit'}}]),
      ] },
    ],
  },
  {
    id:'u6', color:'#00B89C', icon:'⚖️',
    title:{de:'Deine Grundrechte', en:'Your fundamental rights'},
    blurb:{de:'Fälle knacken wie ein Profi', en:'Crack cases like a pro'},
    lessons:[
      { id:'u6l1', xp:20, title:{de:'Grundrechte-Basics', en:'Rights basics'}, exercises:[
        info({de:'Grundrechte schützen dich vor dem Staat: Meinungsfreiheit, Versammlungsfreiheit, Datenschutz und Gleichheit vor dem Gesetz.', en:'Fundamental rights protect you from the state: free speech, assembly, privacy and equality before the law.'}, 'wave'),
        mc({de:'Wovor schützen dich Grundrechte in erster Linie?', en:'Who do fundamental rights primarily protect you from?'},
           [{de:'Vor dem Staat', en:'The state'},{de:'Vor Nachbarn', en:'Your neighbours'},{de:'Vor Firmen', en:'Companies'},{de:'Vor dem Wetter', en:'The weather'}], 0,
           {hint:{de:'Grundrechte sind Abwehrrechte gegenüber staatlicher Macht.', en:'They are defensive rights against state power.'}}),
        tf({de:'Meinungsfreiheit erlaubt auch Verleumdung und gefährliche Drohungen.', en:'Free speech also covers defamation and dangerous threats.'},
           false, {de:'Meinungsfreiheit hat Grenzen – etwa Ehrenbeleidigung, Verhetzung und Drohungen.', en:'Free speech has limits – e.g. defamation, incitement and threats.'}),
        gap({de:'Alle Menschen sind vor dem Gesetz ___.', en:'All people are ___ before the law.'},
           [{de:'gleich', en:'equal'},{de:'anonym', en:'anonymous'},{de:'reich', en:'rich'}], 0),
        match({de:'Ordne die Grundrechte zu.', en:'Match the rights.'},
           [{a:{de:'Meinungsfreiheit', en:'Free speech'}, b:{de:'sagen, was du denkst', en:'say what you think'}},
            {a:{de:'Versammlungsfreiheit', en:'Assembly'}, b:{de:'friedlich demonstrieren', en:'protest peacefully'}},
            {a:{de:'Datenschutz', en:'Privacy'}, b:{de:'deine Daten gehören dir', en:'your data is yours'}},
            {a:{de:'Gleichheit', en:'Equality'}, b:{de:'keine Willkür', en:'no arbitrariness'}}]),
      ]},
      { id:'u6l2', xp:30, title:{de:'Der Fall: Kaputte Kopfhörer', en:'The case: broken headphones'}, exercises:[
        info({de:'Jetzt wird’s praktisch! Avo zeigt dir einen echten Fall – du entscheidest Schritt für Schritt.', en:'Time to get practical! Avo shows you a real case – you decide step by step.'}, 'fire'),
        caseMc({de:'Mia (17) kauft online Kopfhörer um 89 €. Nach 5 Tagen knackt der linke Hörer. Der Shop schreibt: „Wenden Sie sich an den Hersteller.“', en:'Mia (17) buys €89 headphones online. After 5 days the left cup crackles. The shop says: “Contact the manufacturer.”'},
           {de:'Stimmt das? An wen kann sich Mia halten?', en:'Is that right? Who can Mia turn to?'},
           [{de:'An den Shop – er ist ihr Vertragspartner', en:'The shop – it’s her contract partner'},{de:'Nur an den Hersteller', en:'Only the manufacturer'},{de:'An niemanden', en:'No one'},{de:'An die Post', en:'The postal service'}], 0,
           {hint:{de:'Gewährleistung richtet sich immer gegen den Verkäufer.', en:'Warranty claims always target the seller.'}}),
        caseMc({de:'Der Shop lenkt ein, will aber nur einen 20-€-Gutschein geben.', en:'The shop gives in but only offers a €20 voucher.'},
           {de:'Was kann Mia zuerst verlangen?', en:'What can Mia demand first?'},
           [{de:'Reparatur oder Austausch', en:'Repair or replacement'},{de:'Nur den Gutschein', en:'Only the voucher'},{de:'Schmerzensgeld', en:'Damages for pain'},{de:'Nichts – 5 Tage sind zu lang', en:'Nothing – 5 days is too long'}], 0),
        caseMc({de:'Der Shop reagiert 3 Wochen lang gar nicht mehr.', en:'The shop then goes silent for 3 weeks.'},
           {de:'Was ist Mias klügster nächster Schritt?', en:'What is Mia’s smartest next step?'},
           [{de:'Schriftlich reklamieren und Frist setzen', en:'Complain in writing and set a deadline'},{de:'Schlechte Bewertung und vergessen', en:'Bad review, then forget it'},{de:'Sofort klagen', en:'Sue immediately'},{de:'Neue Kopfhörer kaufen', en:'Buy new headphones'}], 0,
           {hint:{de:'Erst Frist setzen – danach Preisminderung oder Rücktritt.', en:'Set a deadline first – then price reduction or withdrawal.'}}),
        tf({de:'Weil Mia minderjährig ist, hat sie gar keine Gewährleistungsrechte.', en:'Because Mia is a minor she has no warranty rights at all.'},
           false, {de:'Gewährleistung gilt für alle Käufer:innen – auch für Jugendliche.', en:'Warranty protects all buyers – teens included.'}),
      ]},
      { id:'u6l3', xp:30, title:{de:'Schritt für Schritt zum Recht', en:'Step by step to justice'}, exercises:[
        info({de:'Wenn Reden nichts hilft, gibt es einen klaren Weg: reklamieren, Frist setzen, Schlichtung, Klage. Immer in dieser Reihenfolge!', en:'If talking fails there’s a clear path: complain, set a deadline, mediation, court. Always in that order!'}),
        order({de:'Mias Weg zum Recht – in der richtigen Reihenfolge:', en:'Mia’s path to justice – in the right order:'},
           [{de:'Mangel schriftlich reklamieren', en:'Complain about the defect in writing'},
            {de:'Angemessene Frist setzen', en:'Set a reasonable deadline'},
            {de:'Schlichtungsstelle einschalten', en:'Involve a mediation body'},
            {de:'Klage bei Gericht einbringen', en:'File a claim in court'}]),
        mc({de:'Wofür ist eine Schlichtungsstelle gut?', en:'What is a mediation body good for?'},
           [{de:'Streit lösen ohne Gericht – meist gratis', en:'Solving disputes without court – usually free'},{de:'Strafen verhängen', en:'Imposing penalties'},{de:'Verträge schreiben', en:'Writing contracts'},{de:'Werbung prüfen', en:'Checking ads'}], 0),
        order({de:'So läuft ein Zivilprozess ab:', en:'How a civil case runs:'},
           [{de:'Klage einbringen', en:'File the claim'},
            {de:'Verhandlung vor Gericht', en:'Court hearing'},
            {de:'Urteil', en:'Judgment'},
            {de:'Berufung möglich', en:'Appeal possible'}]),
        tf({de:'Für kleine Streitwerte gibt es in Österreich vereinfachte Verfahren beim Bezirksgericht.', en:'For small claims Austria offers simplified proceedings at the district court.'},
           true, {de:'Bis 15.000 € ist das Bezirksgericht zuständig – oft ohne Anwaltspflicht.', en:'Up to €15,000 the district court decides – often no lawyer required.'}),
      ]},
    ],
  },
];
window.COURSE = COURSE;

// onboarding category (ONB.langs order) -> course unit id
const CAT_UNIT = ['u1', 'u2', 'u4', 'u3'];
window.CAT_UNIT = CAT_UNIT;

// short placement quiz for "Mein Level finden" — drawn from across the course
const PLACEMENT = [
  mc({de:'Wie viele Tage R\u00FCcktrittsrecht hast du in der EU bei Online-K\u00E4ufen?', en:'How many days of withdrawal do you have for EU online purchases?'},
     [{de:'7 Tage', en:'7 days'},{de:'14 Tage', en:'14 days'},{de:'30 Tage', en:'30 days'},{de:'Keine', en:'None'}], 1),
  mc({de:'Wie lange gilt die gesetzliche Gew\u00E4hrleistung auf Neuware in \u00D6sterreich?', en:'How long is the legal warranty on new goods in Austria?'},
     [{de:'6 Monate', en:'6 months'},{de:'1 Jahr', en:'1 year'},{de:'2 Jahre', en:'2 years'},{de:'5 Jahre', en:'5 years'}], 2),
  mc({de:'Was wird dir tats\u00E4chlich auf dein Konto ausgezahlt?', en:'What is actually paid into your bank account?'},
     [{de:'Das Brutto', en:'The gross'},{de:'Das Netto', en:'The net'},{de:'Die Lohnsteuer', en:'The wage tax'},{de:'Der SV-Beitrag', en:'Social insurance'}], 1),
  mc({de:'Deine \u201EBank\u201C schickt einen Link und fragt nach deinem Passwort. Was tust du?', en:'Your \u201Cbank\u201D sends a link asking for your password. What do you do?'},
     [{de:'Passwort eingeben', en:'Enter the password'},{de:'Nichts \u2013 das ist Phishing', en:'Nothing \u2013 it\u2019s phishing'},{de:'Link weiterleiten', en:'Forward the link'},{de:'Karte hinterlegen', en:'Save my card'}], 1),
  mc({de:'Wie hoch ist die Mietkaution \u00FCblicherweise h\u00F6chstens?', en:'How high is a rental deposit usually capped?'},
     [{de:'1 Monatsmiete', en:'1 month\u2019s rent'},{de:'3 Monatsmieten', en:'3 months\u2019 rent'},{de:'1 Jahresmiete', en:'a year\u2019s rent'},{de:'Unbegrenzt', en:'Unlimited'}], 1),
];
window.PLACEMENT = PLACEMENT;

// leaderboard demo data
const LEAGUE = [
  {name:'Mara', tag:{de:'Paragraphen-Profi', en:'clause pro'}, xp:842, mascot:'lemon'},
  {name:'Jonas', tag:{de:'Vertrags-Held', en:'contract hero'}, xp:790, mascot:'tomato'},
  {name:'Lena', tag:{de:'Akten-Adler', en:'file eagle'}, xp:655, mascot:'gurke'},
  {name:'__you__', tag:{de:'angehende:r Avocat', en:'avocado-in-training'}, xp:0, mascot:'avo'},
  {name:'Ben', tag:{de:'Klausel-Knacker', en:'clause cracker'}, xp:430, mascot:'olive'},
  {name:'Chiara', tag:{de:'Frist-Fuchs', en:'deadline fox'}, xp:388, mascot:'pepper'},
  {name:'Sara', tag:{de:'Recht-Rookie', en:'law rookie'}, xp:312, mascot:'tomato'},
  {name:'Felix', tag:{de:'Mahnungs-Meister', en:'notice master'}, xp:266, mascot:'lemon'},
  {name:'Nina', tag:{de:'Vertrags-Detektivin', en:'contract sleuth'}, xp:241, mascot:'olive'},
  {name:'Tom', tag:{de:'frisch dabei', en:'just joined'}, xp:204, mascot:'gurke'},
  {name:'Yusuf', tag:{de:'Klausel-Kenner', en:'clause buff'}, xp:178, mascot:'pepper'},
  {name:'Emma', tag:{de:'Mietrecht-Maus', en:'tenancy whiz'}, xp:140, mascot:'tomato'},
  {name:'Paul', tag:{de:'Neuling', en:'newcomer'}, xp:96, mascot:'gurke'},
  {name:'Lea', tag:{de:'gerade gestartet', en:'just started'}, xp:54, mascot:'lemon'},
  {name:'Max', tag:{de:'Tag 1', en:'day one'}, xp:22, mascot:'olive'},
];
window.LEAGUE = LEAGUE;
/* sync */
